---
title: "A Framework for Inserting Visually Supported Inferences into Geographical Analysis Workflow: Application to Road Safety Research"
description: "Roger Beecham and Robin Lovelace (2022). A Framework for Inserting Visually Supported Inferences into Geographical Analysis Workflow: Application to Road Safety Research. *Geographical Analysis*. https://doi.org/10.1111/gean.12338"
date: "2022-01-01"
title-block-banner: false
toc: false
citation-key: "beecham_framework_2022"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Geographical Analysis"
doi: "10.1111/gean.12338"
publication-url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/gean.12338"
authors:
  - "Roger Beecham"
  - "Robin Lovelace"
abstract: "Road safety research is a data-rich field with large social impacts. Like in medical research, the ambition is to build knowledge around risk factors that can save lives. Unlike medical research, road safety research generates empirical findings from messy observational datasets. Records of road crashes contain numerous intersecting categorical variables, dominating patterns that are complicated by confounding and, when conditioning on data to make inferences net of this, observed effects that are subject to uncertainty due to diminishing sample sizes. We demonstrate how visual data analysis approaches can inject rigor into exploratory analysis of such datasets. A framework is presented whereby graphics are used to expose, model and evaluate spatial patterns in observational data, as well as protect against false discovery. Evidence for the framework is presented through an applied data analysis of national crash patterns recorded in STATS19, the main source of road crash information in Great Britain. Our framework moves beyond typical depictions of exploratory data analysis and transfers to complex data analysis decision spaces characteristic of modern geographical analysis."
---

**Type:** Journal Article
**Venue:** Geographical Analysis
**Year:** 2022

[DOI](https://doi.org/10.1111/gean.12338) [Publisher Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/gean.12338) [BibTeX](entry.bib)

## Abstract

Road safety research is a data-rich field with large social impacts. Like in medical research, the ambition is to build knowledge around risk factors that can save lives. Unlike medical research, road safety research generates empirical findings from messy observational datasets. Records of road crashes contain numerous intersecting categorical variables, dominating patterns that are complicated by confounding and, when conditioning on data to make inferences net of this, observed effects that are subject to uncertainty due to diminishing sample sizes. We demonstrate how visual data analysis approaches can inject rigor into exploratory analysis of such datasets. A framework is presented whereby graphics are used to expose, model and evaluate spatial patterns in observational data, as well as protect against false discovery. Evidence for the framework is presented through an applied data analysis of national crash patterns recorded in STATS19, the main source of road crash information in Great Britain. Our framework moves beyond typical depictions of exploratory data analysis and transfers to complex data analysis decision spaces characteristic of modern geographical analysis.

## Citation

Roger Beecham and Robin Lovelace (2022). A Framework for Inserting Visually Supported Inferences into Geographical Analysis Workflow: Application to Road Safety Research. *Geographical Analysis*. https://doi.org/10.1111/gean.12338

## BibTeX

```bibtex
@article{beecham_framework_2022,
  title = {A {{Framework}} for {{Inserting Visually Supported Inferences}} into {{Geographical Analysis Workflow}}: {{Application}} to {{Road Safety Research}}},
  shorttitle = {A {{Framework}} for {{Inserting Visually Supported Inferences}} into {{Geographical Analysis Workflow}}},
  author = {Beecham, Roger and Lovelace, Robin},
  date = {2022},
  journaltitle = {Geographical Analysis},
  volume = {n/a},
  number = {n/a},
  issn = {1538-4632},
  doi = {10.1111/gean.12338},
  url = {https://onlinelibrary.wiley.com/doi/abs/10.1111/gean.12338},
  urldate = {2022-07-08},
  abstract = {Road safety research is a data-rich field with large social impacts. Like in medical research, the ambition is to build knowledge around risk factors that can save lives. Unlike medical research, road safety research generates empirical findings from messy observational datasets. Records of road crashes contain numerous intersecting categorical variables, dominating patterns that are complicated by confounding and, when conditioning on data to make inferences net of this, observed effects that are subject to uncertainty due to diminishing sample sizes. We demonstrate how visual data analysis approaches can inject rigor into exploratory analysis of such datasets. A framework is presented whereby graphics are used to expose, model and evaluate spatial patterns in observational data, as well as protect against false discovery. Evidence for the framework is presented through an applied data analysis of national crash patterns recorded in STATS19, the main source of road crash information in Great Britain. Our framework moves beyond typical depictions of exploratory data analysis and transfers to complex data analysis decision spaces characteristic of modern geographical analysis.},
  langid = {english},
  file = {/home/robin/Zotero/storage/C8PK67D9/Beecham and Lovelace - 2022 - A Framework for Inserting Visually Supported Infer.pdf}
}
```

## Notes

{{< include _notes.qmd >}}
