project:
  type: website
  output-dir: _site
  pre-render: scripts/generate_upcoming_events.py
  resources:
    - _redirects

# Meta
description-meta: "Personal website of Robin Lovelace"
author-meta: "Robin Lovelace"

website:
  title: "Robin Lovelace"
  image: "files/images/avatar.jpg"
  description: "Personal website of Robin Lovelace"
 
  navbar:
    background: light  # You can change the background color here
    pinned: false

    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/
      - text: Software
        href: software/
      - text: Projects
        href: projects/
      - text: Events
        href: events/
      - text: Publications
        href: publications/
      - text: Teaching
        href: teaching/
      - text: People
        href: people/
      - text: Contact
        href: contact/

    right: 
      - icon: github
        href: https://github.com/Robinlovelace
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Robin Lovelace](https://github.com/Robinlovelace) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built with [Quarto](https://quarto.org)"
    right:  
      - icon: github
        href: https://github.com/Robinlovelace/robinlovelace.github.io
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: visible
  
  repo-url: https://robinlovelace.net
  
  open-graph: true
  
  twitter-card: true 

  site-url: "https://robinlovelace.net"
bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/robinlovelace\.net\/'
    include-in-header: "files/includes/_academic.qmd"

