---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# robinlovelace

This is the source code of my website.
I plan to store notes on how to use it here.

New talk:


```{bash, eval=FALSE}
hugo new  --kind event event/ogh23
cp -Rv content/event/sdsl2024 content/event/glasgow2024
code content/event/glasgow2024/index.md
```

```{r, eval=FALSE}
file.edit("content/event/modeshift-2022/index.md")
blogdown::install_hugo()

# new blog post:
blogdown::new_post(title = "2024-retrospective", ext = ".Rmd")

blogdown::new_content(path = "software/index.Rmd")

# serve site
blogdown::serve_site()

# build site
blogdown::build_site()
```

To update publications run:

```bash
# pip3 install academic==0.5.1
# pip3 install academic==0.11.2
# Update:
pip install --upgrade academic
# overwrite existing:
# academic import --bibtex static/bibs/my-citations-for-web.bib --over 
academic import --bibtex static/bibs/my-citations-for-web.bib
```


