---
title: "Where to invest in cycle parking: A portfolio management approach to spatial transport planning"
description: "Yuhei Ito, Malcolm Morgan, and Robin Lovelace (2023). Where to invest in cycle parking: A portfolio management approach to spatial transport planning. *Environment and Planning B: Urban Analytics and City Science*. https://doi.org/10.1177/23998083221138575"
date: "2023-07-01"
title-block-banner: false
toc: false
citation-key: "ito_where_2023"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Environment and Planning B: Urban Analytics and City Science"
doi: "10.1177/23998083221138575"
publication-url: "https://doi.org/10.1177/23998083221138575"
authors:
  - "Yuhei Ito"
  - "Malcolm Morgan"
  - "Robin Lovelace"
abstract: "A lack of cycle parking is a known barrier to promoting the uptake of cycling in urban areas. Unlike cars that can be parked on the roadside with little additional infrastructure, bikes usually require dedicated parking facilities. The existing research and guidance on where cycle parking should be provided primarily focuses on key destinations such as train stations or schools. Thus, there is a gap in knowledge about the amount of general-purpose cycle parking required and how it should be distributed across a city. This paper presents a novel method for analysing and prioritising the spatial distribution of cycle parking. The method draws on established portfolio management techniques but applies them in a spatial context. Using the case study of London, we demonstrate that it is possible to identify areas that have a deficit of cycle parking as well as locations that have the most significant potential for increasing cycling uptake by providing additional cycle parking."
---

**Type:** Journal Article
**Venue:** Environment and Planning B: Urban Analytics and City Science
**Year:** 2023

[DOI](https://doi.org/10.1177/23998083221138575) [URL](https://doi.org/10.1177/23998083221138575) [BibTeX](entry.bib)

## Abstract

A lack of cycle parking is a known barrier to promoting the uptake of cycling in urban areas. Unlike cars that can be parked on the roadside with little additional infrastructure, bikes usually require dedicated parking facilities. The existing research and guidance on where cycle parking should be provided primarily focuses on key destinations such as train stations or schools. Thus, there is a gap in knowledge about the amount of general-purpose cycle parking required and how it should be distributed across a city. This paper presents a novel method for analysing and prioritising the spatial distribution of cycle parking. The method draws on established portfolio management techniques but applies them in a spatial context. Using the case study of London, we demonstrate that it is possible to identify areas that have a deficit of cycle parking as well as locations that have the most significant potential for increasing cycling uptake by providing additional cycle parking.

## Citation

Yuhei Ito, Malcolm Morgan, and Robin Lovelace (2023). Where to invest in cycle parking: A portfolio management approach to spatial transport planning. *Environment and Planning B: Urban Analytics and City Science*. https://doi.org/10.1177/23998083221138575

## BibTeX

```bibtex
@article{ito_where_2023,
  title = {Where to Invest in Cycle Parking: {{A}} Portfolio Management Approach to Spatial Transport Planning},
  shorttitle = {Where to Invest in Cycle Parking},
  author = {Ito, Yuhei and Morgan, Malcolm and Lovelace, Robin},
  date = {2023-07-01},
  journaltitle = {Environment and Planning B: Urban Analytics and City Science},
  volume = {50},
  number = {6},
  pages = {1438--1454},
  publisher = {SAGE Publications Ltd STM},
  issn = {2399-8083},
  doi = {10.1177/23998083221138575},
  url = {https://doi.org/10.1177/23998083221138575},
  urldate = {2023-12-31},
  abstract = {A lack of cycle parking is a known barrier to promoting the uptake of cycling in urban areas. Unlike cars that can be parked on the roadside with little additional infrastructure, bikes usually require dedicated parking facilities. The existing research and guidance on where cycle parking should be provided primarily focuses on key destinations such as train stations or schools. Thus, there is a gap in knowledge about the amount of general-purpose cycle parking required and how it should be distributed across a city. This paper presents a novel method for analysing and prioritising the spatial distribution of cycle parking. The method draws on established portfolio management techniques but applies them in a spatial context. Using the case study of London, we demonstrate that it is possible to identify areas that have a deficit of cycle parking as well as locations that have the most significant potential for increasing cycling uptake by providing additional cycle parking.},
  langid = {english},
  annotation = {0 citations (Crossref) [2023-12-31]},
  file = {/home/robin/Zotero/storage/5CL47NPH/Ito et al. - 2022 - Where to invest in cycle parking A portfolio mana.pdf;/home/robin/Zotero/storage/UQDU2BR3/Ito et al. - 2023 - Where to invest in cycle parking A portfolio mana.pdf}
}
```

## Notes

{{< include _notes.qmd >}}
