---
title: "Health, environmental and distributional impacts of cycling uptake: The model underlying the Propensity to Cycle tool for England and Wales"
description: "James Woodcock, Rachel Aldred, Robin Lovelace, Tessa Strain, and Anna Goodman (2021). Health, environmental and distributional impacts of cycling uptake: The model underlying the Propensity to Cycle tool for England and Wales. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2021.101066"
date: "2021-09-01"
title-block-banner: false
toc: false
citation-key: "woodcock_health_2021a"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Transport & Health"
doi: "10.1016/j.jth.2021.101066"
publication-url: ""
authors:
  - "James Woodcock"
  - "Rachel Aldred"
  - "Robin Lovelace"
  - "Tessa Strain"
  - "Anna Goodman"
abstract: "Introduction The Propensity to Cycle Tool (PCT) is a widely used free, open source and publicly available tool for modelling cycling uptake and corresponding health and carbon impacts in England and Wales. In this paper we present the methods for our new individual-level modelling representing all commuters in England and Wales. Methods Scenario commuter cycling potential in the PCT is modelled as a function of route distance and hilliness between home and work. Our new individual-level approach has allowed us to create an additional “Near Market” scenario where age, gender, ethnicity, car ownership and area level deprivation also affect an individual’s likelihood of switching to cycling. For this and other scenarios, we calculate the carbon benefits of cycling uptake based on the trip distance and previous mode, while health benefits are additionally affected by hilliness and baseline average mortality risk. This allows the estimation of how health and carbon benefits differ by demographic group as well as by scenario. Results While cycle commuting in England and Wales is demographically skewed towards men and white people, women and people from ethnic minorities have greater cycling potential based on route distance and hilliness. Benefits from cycling uptake are distributed differently again. For example, while increasing female cycling mode share is good for equity, each additional female cyclist generates a smaller average health and carbon benefit than a male cyclist. This is based on women’s lower baseline mortality risk, shorter commute travel distances, and lower propensity to commute by car than men. Conclusion We have demonstrated a new approach to modelling that allows for more sophisticated and nuanced assessment of cycling uptake and subsequent benefits, under different scenarios. Health and carbon are increasingly incorporated into appraisal of active travel schemes, valuing important outcomes. However, especially with better representation of demographic factors, this can act as a barrier to equity goals."
---

**Type:** Journal Article
**Venue:** Journal of Transport & Health
**Year:** 2021

[DOI](https://doi.org/10.1016/j.jth.2021.101066) [BibTeX](entry.bib)

## Abstract

Introduction The Propensity to Cycle Tool (PCT) is a widely used free, open source and publicly available tool for modelling cycling uptake and corresponding health and carbon impacts in England and Wales. In this paper we present the methods for our new individual-level modelling representing all commuters in England and Wales. Methods Scenario commuter cycling potential in the PCT is modelled as a function of route distance and hilliness between home and work. Our new individual-level approach has allowed us to create an additional “Near Market” scenario where age, gender, ethnicity, car ownership and area level deprivation also affect an individual’s likelihood of switching to cycling. For this and other scenarios, we calculate the carbon benefits of cycling uptake based on the trip distance and previous mode, while health benefits are additionally affected by hilliness and baseline average mortality risk. This allows the estimation of how health and carbon benefits differ by demographic group as well as by scenario. Results While cycle commuting in England and Wales is demographically skewed towards men and white people, women and people from ethnic minorities have greater cycling potential based on route distance and hilliness. Benefits from cycling uptake are distributed differently again. For example, while increasing female cycling mode share is good for equity, each additional female cyclist generates a smaller average health and carbon benefit than a male cyclist. This is based on women’s lower baseline mortality risk, shorter commute travel distances, and lower propensity to commute by car than men. Conclusion We have demonstrated a new approach to modelling that allows for more sophisticated and nuanced assessment of cycling uptake and subsequent benefits, under different scenarios. Health and carbon are increasingly incorporated into appraisal of active travel schemes, valuing important outcomes. However, especially with better representation of demographic factors, this can act as a barrier to equity goals.

## Citation

James Woodcock, Rachel Aldred, Robin Lovelace, Tessa Strain, and Anna Goodman (2021). Health, environmental and distributional impacts of cycling uptake: The model underlying the Propensity to Cycle tool for England and Wales. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2021.101066

## BibTeX

```bibtex
@article{woodcock_health_2021a,
  title = {Health, Environmental and Distributional Impacts of Cycling Uptake: {{The}} Model Underlying the {{Propensity}} to {{Cycle}} Tool for {{England}} and {{Wales}}},
  shorttitle = {Health, Environmental and Distributional Impacts of Cycling Uptake},
  author = {Woodcock, James and Aldred, Rachel and Lovelace, Robin and Strain, Tessa and Goodman, Anna},
  year = {2021},
  month = sep,
  journal = {Journal of Transport \& Health},
  volume = {22},
  pages = {101066},
  issn = {2214-1405},
  doi = {10.1016/j.jth.2021.101066},
  urldate = {2021-06-24},
  abstract = {Introduction The Propensity to Cycle Tool (PCT) is a widely used free, open source and publicly available tool for modelling cycling uptake and corresponding health and carbon impacts in England and Wales. In this paper we present the methods for our new individual-level modelling representing all commuters in England and Wales. Methods Scenario commuter cycling potential in the PCT is modelled as a function of route distance and hilliness between home and work. Our new individual-level approach has allowed us to create an additional ``Near Market'' scenario where age, gender, ethnicity, car ownership and area level deprivation also affect an individual's likelihood of switching to cycling. For this and other scenarios, we calculate the carbon benefits of cycling uptake based on the trip distance and previous mode, while health benefits are additionally affected by hilliness and baseline average mortality risk. This allows the estimation of how health and carbon benefits differ by demographic group as well as by scenario. Results While cycle commuting in England and Wales is demographically skewed towards men and white people, women and people from ethnic minorities have greater cycling potential based on route distance and hilliness. Benefits from cycling uptake are distributed differently again. For example, while increasing female cycling mode share is good for equity, each additional female cyclist generates a smaller average health and carbon benefit than a male cyclist. This is based on women's lower baseline mortality risk, shorter commute travel distances, and lower propensity to commute by car than men. Conclusion We have demonstrated a new approach to modelling that allows for more sophisticated and nuanced assessment of cycling uptake and subsequent benefits, under different scenarios. Health and carbon are increasingly incorporated into appraisal of active travel schemes, valuing important outcomes. However, especially with better representation of demographic factors, this can act as a barrier to equity goals.},
  copyright = {CC0 1.0 Universal Public Domain Dedication},
  langid = {english},
  keywords = {Appraisal,Carbon,Cycling,Equity,Health impact modelling},
  file = {/home/robin/Zotero/storage/ST7JFGPJ/Woodcock et al. - 2021 - Health, environmental and distributional impacts o.pdf;/home/robin/Zotero/storage/V5ACFWUW/S2214140521000967.html}
}
```

## Notes

{{< include _notes.qmd >}}
