---
title: "Open source tools for geographic analysis in transport planning"
description: "Robin Lovelace (2021). Open source tools for geographic analysis in transport planning. *Journal of Geographical Systems*. https://doi.org/10.1007/s10109-020-00342-2"
date: "2021-10-01"
title-block-banner: false
toc: false
citation-key: "lovelace_open_2021"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Geographical Systems"
doi: "10.1007/s10109-020-00342-2"
publication-url: "https://doi.org/10.1007/s10109-020-00342-2"
authors:
  - "Robin Lovelace"
abstract: "Geographic analysis has long supported transport plans that are appropriate to local contexts. Many incumbent “tools of the trade” are proprietary and were developed to support growth in motor traffic, limiting their utility for transport planners who have been tasked with twenty-first century objectives such as enabling citizen participation, reducing pollution, and increasing levels of physical activity by getting more people walking and cycling. Geographic techniques—such as route analysis, network editing, localised impact assessment and interactive map visualisation—have great potential to support modern transport planning priorities. The aim of this paper is to explore emerging open source tools for geographic analysis in transport planning, with reference to the literature and a review of open source tools that are already being used. A key finding is that a growing number of options exist, challenging the current landscape of proprietary tools. These can be classified as command-line interface, graphical user interface or web-based user interface tools and by the framework in which they were implemented, with numerous tools released as R, Python and JavaScript packages, and QGIS plugins. The review found a diverse and rapidly evolving “ecosystem” tools, with 25 tools that were designed for geographic analysis to support transport planning outlined in terms of their popularity and functionality based on online documentation. They ranged in size from single-purpose tools such as the QGIS plugin AwaP to sophisticated stand-alone multi-modal traffic simulation software such as MATSim, SUMO and Veins. Building on their ability to re-use the most effective components from other open source projects, developers of open source transport planning tools can avoid “reinventing the wheel” and focus on innovation, the “gamified” A/B Street https://github.com/dabreegster/abstreet/#abstreetsimulation software, based on OpenStreetMap, a case in point. The paper, the source code of which can be found at https://github.com/robinlovelace/open-gat, concludes that, although many of the tools reviewed are still evolving and further research is needed to understand their relative strengths and barriers to uptake, open source tools for geographic analysis in transport planning already hold great potential to help generate the strategic visions of change and evidence that is needed by transport planners in the twenty-first century."
---

**Type:** Journal Article
**Venue:** Journal of Geographical Systems
**Year:** 2021

[DOI](https://doi.org/10.1007/s10109-020-00342-2) [URL](https://doi.org/10.1007/s10109-020-00342-2) [BibTeX](entry.bib)

## Abstract

Geographic analysis has long supported transport plans that are appropriate to local contexts. Many incumbent “tools of the trade” are proprietary and were developed to support growth in motor traffic, limiting their utility for transport planners who have been tasked with twenty-first century objectives such as enabling citizen participation, reducing pollution, and increasing levels of physical activity by getting more people walking and cycling. Geographic techniques—such as route analysis, network editing, localised impact assessment and interactive map visualisation—have great potential to support modern transport planning priorities. The aim of this paper is to explore emerging open source tools for geographic analysis in transport planning, with reference to the literature and a review of open source tools that are already being used. A key finding is that a growing number of options exist, challenging the current landscape of proprietary tools. These can be classified as command-line interface, graphical user interface or web-based user interface tools and by the framework in which they were implemented, with numerous tools released as R, Python and JavaScript packages, and QGIS plugins. The review found a diverse and rapidly evolving “ecosystem” tools, with 25 tools that were designed for geographic analysis to support transport planning outlined in terms of their popularity and functionality based on online documentation. They ranged in size from single-purpose tools such as the QGIS plugin AwaP to sophisticated stand-alone multi-modal traffic simulation software such as MATSim, SUMO and Veins. Building on their ability to re-use the most effective components from other open source projects, developers of open source transport planning tools can avoid “reinventing the wheel” and focus on innovation, the “gamified” A/B Street https://github.com/dabreegster/abstreet/#abstreetsimulation software, based on OpenStreetMap, a case in point. The paper, the source code of which can be found at https://github.com/robinlovelace/open-gat, concludes that, although many of the tools reviewed are still evolving and further research is needed to understand their relative strengths and barriers to uptake, open source tools for geographic analysis in transport planning already hold great potential to help generate the strategic visions of change and evidence that is needed by transport planners in the twenty-first century.

## Citation

Robin Lovelace (2021). Open source tools for geographic analysis in transport planning. *Journal of Geographical Systems*. https://doi.org/10.1007/s10109-020-00342-2

## BibTeX

```bibtex
@article{lovelace_open_2021,
  title = {Open Source Tools for Geographic Analysis in Transport Planning},
  author = {Lovelace, Robin},
  date = {2021-10-01},
  journaltitle = {Journal of Geographical Systems},
  shortjournal = {J Geogr Syst},
  volume = {23},
  number = {4},
  pages = {547--578},
  issn = {1435-5949},
  doi = {10.1007/s10109-020-00342-2},
  url = {https://doi.org/10.1007/s10109-020-00342-2},
  urldate = {2024-10-06},
  abstract = {Geographic analysis has long supported transport plans that are appropriate to local contexts. Many incumbent ‘tools of the trade’ are proprietary and were developed to support growth in motor traffic, limiting their utility for transport planners who have been tasked with twenty-first century objectives such as enabling citizen participation, reducing pollution, and increasing levels of physical activity by getting more people walking and cycling. Geographic techniques—such as route analysis, network editing, localised impact assessment and interactive map visualisation—have great potential to support modern transport planning priorities. The aim of this paper is to explore emerging open source tools for geographic analysis in transport planning, with reference to the literature and a review of open source tools that are already being used. A key finding is that a growing number of options exist, challenging the current landscape of proprietary tools. These can be classified as command-line interface, graphical user interface or web-based user interface tools and by the framework in which they were implemented, with numerous tools released as R, Python and JavaScript packages, and QGIS plugins. The review found a diverse and rapidly evolving ‘ecosystem’ tools, with 25 tools that were designed for geographic analysis to support transport planning outlined in terms of their popularity and functionality based on online documentation. They ranged in size from single-purpose tools such as the QGIS plugin AwaP to sophisticated stand-alone multi-modal traffic simulation software such as MATSim, SUMO and Veins. Building on their ability to re-use the most effective components from other open source projects, developers of open source transport planning tools can avoid ‘reinventing the wheel’ and focus on innovation, the ‘gamified’ A/B Street https://github.com/dabreegster/abstreet/\#abstreetsimulation software, based on OpenStreetMap, a case in point. The paper, the source code of which can be found at https://github.com/robinlovelace/open-gat, concludes that, although many of the tools reviewed are still evolving and further research is needed to understand their relative strengths and barriers to uptake, open source tools for geographic analysis in transport planning already hold great potential to help generate the strategic visions of change and evidence that is needed by transport planners in the twenty-first century.},
  langid = {english},
  keywords = {Artificial Intelligence,C6,Geographic data,Geographic data analysis,Open source,R41,Software,Transport modelling,Transport planning},
  annotation = {31 citations (Crossref) [2024-10-06]},
  file = {/home/robin/Zotero/storage/N8T7PAQF/Lovelace - 2021 - Open source tools for geographic analysis in trans.pdf}
}
```

## Notes

{{< include _notes.qmd >}}
