---
title: tartu2024
author: ''
date: '2024-06-15'
slug: tartu2024
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2024-06-15T16:10:24+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Last week I attended the [Mobile Tartu conference](https://mobiletartu.ut.ee) 2024.
It was the 9^th^ time that this 2-yearly conference has run, marking 16 years since the first Mobile Tartu in [2008](https://mobiletartu2008.mobilitylab.ut.ee/).
I've been to a lot of conferences in my time, but this one was exceptionally good, containing ingredients for a productive, professional, inclusive and fun event (take note anyone thinking of organising a conference or workshop, including my future self)!
I had a great time and learned loads during many of the sessions, and during the social and down-time in the city of Tartu.

This write-up is my attempt to process the event and follow-up on links to research that I didn't get a chance to during the event itself.
Hopefully these notes will also be of interest, and the content linked-to within of use, to others also.
The conference took place over 4 days (5 including the excursion day on Saturday which I unfortunately could not make, I spend most of 'day 5' on the long journey home during which I wrote much of this blog post).
The location was --- you guessed it from the name --- the Estonian town of Tartu, which is how I (and I suspect many others working in the mobility/transport sector) first heard of it.

# Tuesday 11th June

Tuesday was the first day of the 2-day [PhD School](https://mobiletartu.ut.ee/phd-course/) that preceded and then joined the main conference.
Traditionally it takes place outside the main conference location and this year was no exception: a nature reserve just outside Tartu was the location chosen this year.
There were fun ice-breakers, including a decentralised quiz during which participants were tasked with finding at least one person who met each of a dozen criteria relating to topics including people's favourite GUI-based GIS software (QGIS of course!), ... and Estonian puddings (the hardest criteria because it had to be a non-Estonian who had eaten *and remembered the name of* said hard-to-pronounce pudding).

Even more inclusive was how everyone introduced themselves.
We were asked to stand in a circle looking in and say our name, where we're from and how many 'Mobile Tartus' we had previously attended (number one for me, I was impressed to learn that there were people there who had all 9).
After some refreshments and general mingling it was time for the first keynote talk: Kristjan ... who had spent time on a placement with the Estonian government.
His talk was fascinating to me, as someone who had made the shift from academia to the public sector.
Instead of working on separate jobs --- as I did when I shifted from being on secondment to Active Travel England as part of the 10DS Fellowship to taking on a second job in early 2023 --- Kristjan seems to have gone all-in on the public sector job, and acheived a huge amount.
As far as I am aware, in Estonia (as in many other countries including Germany and perhaps all the nordic nations), being an academic *means* being a civil servant, that is to say: like civil servants, academics in Estonia are employed by the government.

I'm not sure about the distribution of pros and cons of this, but I imagine that it makes it easier for academics to take on government roles (has anyone done research into the extent to which government policies are evidence-based in countries in which academic staff in state universities *are* civil servants, compared with countries in which they are not, I wonder).
The talk was fascinating, covering projects that had involved new and emerging datasets held by the Estonian government.

I already knew that Estonia was an early adopter of 'digital government' but didn't realise the breadth and depth of digital government initiatives and policies it has in place (in fact 'initiatives and policies' don't really do justice to some of these things, digital government seems to have become so embedded that it's simply *how things are done*).
Digital government in Estonia includes (or perhaps more accurately is underpinned by) [X-Road](https://x-road.global/), an [open source](https://github.com/nordic-institute/X-Road) system for secure, decentralised management of multiple government datasets that serves hundreds of thousands of queries every year, saving thousands of person-days worth of work.
The system allows different parts of government to inter-connect, helping with the process of what the Department for Transport's Chief Scientific Advisor calls de-siloisation.
I took some notes during the talk, one of which was the following:

> If you never scale, you'll never have an impact on policy: as Kristjan said it's not enough to put the concept out, write the paper and move on: you need a prototype.

After the talk (which had many other examples of digital government and its clear benefits), we split into four groups for the PhD workshop sessions:

- A team working on datasets representing refugee movements
- A group working on Mobility Hubs
- A team working on data from Helsinki provided by Hennriki Tenkannen, who led the session

Despite not being a PhD student and therefore not having signed-up to a session, I decided to attend Hennriki's session, wanting to brush-up on my Python skills and to check-out some open access transport-related datasets from Finland.

The final part of day 1 was a social which involved optionally going into a sauna and (even more optionally) taking a dip in the river.
Tired from all the activity of the first day we headed to Tartu where the rest of the conference would take place.

# Wednesday 12th

The second day involved a continuation of the PhD workshops, plus the opening of main Mobile Conference for all participants.
There was plenty of time to work on the topics and other things: I decided to work on a related dataset and the nascent [{spanishoddata}](https://github.com/Robinlovelace/spanishoddata) package during some of this time.

# Thursday

The first full day of the conference involved keynote talks by of Nico Van de Weghe from Ghent University and Anu Masso, interspersed with regular talks submitted by part

# Friday

# Saturday