---
bibliography: /home/robin/allrefs.bib
output: md_document
---

## Welcome

Welcome to my website. The aim is to provide a place for getting my work and ideas out there quickly and better linked-in with the wider world. I hope you find something here of use and interest. Enjoy your visit!

## About me

I'm a geographer and environmental scientist specialising in [spatial data analysis](https://www.crcpress.com/Spatial-Microsimulation-with-R/Lovelace-Dumont/p/book/9781498711548) and computing, especially [R programming](https://csgillespie.github.io/efficientR/).

Based at the Leeds Institute for Transport Studies ([ITS](https://www.its.leeds.ac.uk/people/r.lovelace)) I have a strong interest in transport modelling. This is described in a  [review](http://eprints.whiterose.ac.uk/102373/1/urban-travel-rl.pdf) of a [book](http://www.e-elgar.com/shop/forecasting-urban-travel) on the subject by @boyce_forecasting_2015.

I studied Geography at the [University of Bristol](http://www.bristol.ac.uk/geography/) after moving out of my home town of Hereford where I went to [Weobley High School](http://weobleyhigh.co.uk/), out in rural Northwest Herefordshire, and then Hereford [Sixth Form College](http://www.hereford.ac.uk/). 

From an early age I enjoyed travelling. Since moving to Bristol to settling in Leeds for my current job I have moved 3 times:

- To Salamanca in 2006 for a year studying at the [Universidad de Salamanca](http://www.usal.es/) on the Erasmus scheme, where I learned Spanish, before completing my degree in Bristol.

- To York in 2008 for a scholarship on the [Environmental Science and Management](https://www.york.ac.uk/study/postgraduate/courses/msc-environmental-science-management/) master's course at the [University of York](https://www.york.ac.uk/).

- To Sheffield in 2009 to do a PhD in energy and transport at the [University of Sheffield](http://shef.ac.uk/) as part of the [E-Futures](http://e-futures.group.shef.ac.uk/page/home/) centre.

I moved ([by bicycle trailer!](https://www.youtube.com/watch?v=6a8QLiC4LV8)) from Sheffield to Leeds in summer 2013 for a post-doctorate job in Geospatial Data Analysis and Simulation ([TALISMAN](http://www.researchcatalogue.esrc.ac.uk/grants/RES-576-25-0039/read)). A year later I got a job at the Leeds Institute for Data Analytics ([LIDA](http://lida.leeds.ac.uk/)) where I am still based alongside my role in ITS.

I have been based at the Leeds Institute for Transport Studies ([ITS](https://www.its.leeds.ac.uk)) since September 2016 as a University Academic Fellow in Transport and Big Data.  Here I work on researching the energy impacts of transport systems, modelling the uptake of sustainable transport uptake, new methods on transport geography and visualizing transport futures at a local level.

## Applied work

I've applied my skills to a number of projects with real-world applications, most recently the Propensity to Cycle Tool (PCT) for the Department for Transport [@lovelace_propensity_2017]. The PCT is a national project which maps future cycling potential with the aim of helping to design more sustainable cities. A central output of the PCT is a publicly accessible map. If you live in England, you can check out current and potential future levels of cycling in your local area by visiting [www.pct.bike](http://www.pct.bike/) and clicking on where you live. 

I also develop [stplanr](https://github.com/ropensci/stplanr), an R package for sustainable transport planning.

## About this website

This website was built using open source software. It uses [Hugo](https://gohugo.io/), a static website generator written in Go, and [blogdown](https://bookdown.org/yihui/blogdown/), an R package by Yihui Xie writing posts that contain embedded code. Its source code can be found at [github.com/rbind/robinlovelace](https://github.com/rbind/robinlovelace).

If you're interested in my earlier work, please check-out:

- Other posts by me on [R-Bloggers](https://www.r-bloggers.com/author/robin-lovelace-r/).

- My old Wordpress site at [robinlovelace.wordpress.com/](https://robinlovelace.wordpress.com/).

- Older posts hosted on an [earlier version of this website](http://robinlovelace.net/old-site.html).

- My YouTube channel at [youtube.com/robinlovelace](https://www.youtube.com/robinlovelace).

## References