---
title: "Methods to Prioritise Pop-up Active Transport Infrastructure"
description: "Robin Lovelace, Joseph Talbot, Malcolm Morgan, and Martin Lucas-Smith (2020). Methods to Prioritise Pop-up Active Transport Infrastructure. *Transport Findings*. https://doi.org/10.32866/001c.13421"
date: "2020-07-01"
title-block-banner: false
toc: false
citation-key: "lovelace_methods_2020"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Transport Findings"
doi: "10.32866/001c.13421"
publication-url: "https://transportfindings.org/article/13421-methods-to-prioritise-pop-up-active-transport-infrastructure"
authors:
  - "Robin Lovelace"
  - "Joseph Talbot"
  - "Malcolm Morgan"
  - "Martin Lucas-Smith"
abstract: "In the context of reduced public transport capacity in the wake of the COVID-19 pandemic, governments are scrambling to enable walking and cycling while adhering to physical distancing guidelines. Many pop-up options exist. Of these, road space reallocation represents a “quick win” for cities with “spare space” along continuous road sections that have high latent cycling potential. We developed methods to condense the complexity of city networks down to the most promising roads for road space reallocation schemes. The resulting Rapid Cycleway Prioritisation Tool has been deployed for all cities in England to help prioritise emergency funds for new cycleways nationwide. The methods and concepts could be used to support investment in pop-up infrastructure in cities worldwide."
---

**Type:** Journal Article
**Venue:** Transport Findings
**Year:** 2020

[DOI](https://doi.org/10.32866/001c.13421) [Publisher Link](https://transportfindings.org/article/13421-methods-to-prioritise-pop-up-active-transport-infrastructure) [BibTeX](entry.bib)

## Abstract

In the context of reduced public transport capacity in the wake of the COVID-19 pandemic, governments are scrambling to enable walking and cycling while adhering to physical distancing guidelines. Many pop-up options exist. Of these, road space reallocation represents a “quick win” for cities with “spare space” along continuous road sections that have high latent cycling potential. We developed methods to condense the complexity of city networks down to the most promising roads for road space reallocation schemes. The resulting Rapid Cycleway Prioritisation Tool has been deployed for all cities in England to help prioritise emergency funds for new cycleways nationwide. The methods and concepts could be used to support investment in pop-up infrastructure in cities worldwide.

## Citation

Robin Lovelace, Joseph Talbot, Malcolm Morgan, and Martin Lucas-Smith (2020). Methods to Prioritise Pop-up Active Transport Infrastructure. *Transport Findings*. https://doi.org/10.32866/001c.13421

## BibTeX

```bibtex
@article{lovelace_methods_2020,
	title = {Methods to {Prioritise} {Pop}-up {Active} {Transport} {Infrastructure}},
	copyright = {CC0 1.0 Universal Public Domain Dedication},
	url = {https://transportfindings.org/article/13421-methods-to-prioritise-pop-up-active-transport-infrastructure},
	doi = {10.32866/001c.13421},
	abstract = {In the context of reduced public transport capacity in the wake of the COVID-19 pandemic, governments are scrambling to enable walking and cycling while adhering to physical distancing guidelines. Many pop-up options exist. Of these, road space reallocation represents a ‘quick win’ for cities with ‘spare space’ along continuous road sections that have high latent cycling potential. We developed methods to condense the complexity of city networks down to the most promising roads for road space reallocation schemes. The resulting Rapid Cycleway Prioritisation Tool has been deployed for all cities in England to help prioritise emergency funds for new cycleways nationwide. The methods and concepts could be used to support investment in pop-up infrastructure in cities worldwide.},
	language = {en},
	urldate = {2020-07-08},
	journal = {Transport Findings},
	publisher = {Network Design Lab},
	author = {Lovelace, Robin and Talbot, Joseph and Morgan, Malcolm and Lucas-Smith, Martin},
	month = jul,
	year = {2020},
	note = {tex.ids= Lovelace2020Methods},
	pages = {13421},
}
```

## Notes

{{< include _notes.qmd >}}
