---
title: "Active Travel Oriented Development: Assessing the suitability of sites for new homes"
description: "Joseph Talbot, Martin Lucas-Smith, Andrew Speakman, Megan Streb, Simon Nuttall, Dustin Carlino, Patrick Johansson, Nathanael Sheehan, Nikée Groot, and Robin Lovelace (2021). Active Travel Oriented Development: Assessing the suitability of sites for new homes. *OSF Preprints*. https://doi.org/10.31219/osf.io/7fuq5"
date: "2021-09-01"
title-block-banner: false
toc: false
citation-key: "talbot_active_2021"
citation-type: "report"
citation-type-label: "Report"
venue: "OSF Preprints"
doi: "10.31219/osf.io/7fuq5"
publication-url: "https://osf.io/7fuq5/"
authors:
  - "Joseph Talbot"
  - "Martin Lucas-Smith"
  - "Andrew Speakman"
  - "Megan Streb"
  - "Simon Nuttall"
  - "Dustin Carlino"
  - "Patrick Johansson"
  - "Nathanael Sheehan"
  - "Nikée Groot"
  - "Robin Lovelace"
abstract: "The location of new housing developments, and the provision of safe space for walking and cycling to key destinations around them, have major and long lasting impacts on travel behaviour, health, and environmental outcomes. Transit Oriented Development (TOD) is a well-recognised concept in urban planning, but systemic evidence is often lacking on the likely “active travel performance” of new developments, making it hard for the planning process to support sustainable transport objectives. This paper articulates the concept of “Active Travel Oriented Development” (ATOD) and describes methods for operationalising it. We demonstrate the use of a set of simple metrics to assess the active travel performance of new and proposed development sites. ATOD has the benefits of building on the established concept of TOD and being easy to assess. We conclude that ATOD, and tools for measuring it, are needed to ensure that transport and development policies work in harmony."
---

**Type:** Report
**Venue:** OSF Preprints
**Year:** 2021

[DOI](https://doi.org/10.31219/osf.io/7fuq5) [Publisher Link](https://osf.io/7fuq5/) [BibTeX](entry.bib)

## Abstract

The location of new housing developments, and the provision of safe space for walking and cycling to key destinations around them, have major and long lasting impacts on travel behaviour, health, and environmental outcomes. Transit Oriented Development (TOD) is a well-recognised concept in urban planning, but systemic evidence is often lacking on the likely “active travel performance” of new developments, making it hard for the planning process to support sustainable transport objectives. This paper articulates the concept of “Active Travel Oriented Development” (ATOD) and describes methods for operationalising it. We demonstrate the use of a set of simple metrics to assess the active travel performance of new and proposed development sites. ATOD has the benefits of building on the established concept of TOD and being easy to assess. We conclude that ATOD, and tools for measuring it, are needed to ensure that transport and development policies work in harmony.

## Citation

Joseph Talbot, Martin Lucas-Smith, Andrew Speakman, Megan Streb, Simon Nuttall, Dustin Carlino, Patrick Johansson, Nathanael Sheehan, Nikée Groot, and Robin Lovelace (2021). Active Travel Oriented Development: Assessing the suitability of sites for new homes. *OSF Preprints*. https://doi.org/10.31219/osf.io/7fuq5

## BibTeX

```bibtex
@techreport{talbot_active_2021,
	title = {Active {Travel} {Oriented} {Development}: {Assessing} the suitability of sites for new homes},
	copyright = {CC0 1.0 Universal Public Domain Dedication},
	shorttitle = {Active {Travel} {Oriented} {Development}},
	url = {https://osf.io/7fuq5/},
	doi = {10.31219/osf.io/7fuq5},
	abstract = {The location of new housing developments, and the provision of safe space for walking and cycling to key destinations around them, have major and long lasting impacts on travel behaviour, health, and environmental outcomes. Transit Oriented Development (TOD) is a well-recognised concept in urban planning, but systemic evidence is often lacking on the likely ‘active travel performance’ of new developments, making it hard for the planning process to support sustainable transport objectives. This paper articulates the concept of
‘Active Travel Oriented Development’ (ATOD) and describes methods for operationalising it. We demonstrate the use of a set of simple metrics to assess the active travel performance of new and proposed development sites. ATOD has the benefits of building on the established concept of TOD and being easy to assess. We conclude that ATOD, and tools for measuring it, are needed to ensure that transport and development policies work in harmony.},
	urldate = {2021-09-28},
	institution = {OSF Preprints},
	author = {Talbot, Joseph and Lucas-Smith, Martin and Speakman, Andrew and Streb, Megan and Nuttall, Simon and Carlino, Dustin and Johansson, Patrick and Sheehan, Nathanael and Groot, Nikée and Lovelace, Robin},
	month = sep,
	year = {2021},
	note = {type: article},
	keywords = {Geography, Social and Behavioral Sciences, Spatial Science, Urban Studies and Planning, active travel, planning, residential development, transport},
}
```

## Notes

{{< include _notes.qmd >}}
