---
title: "Reproducible methods for network simplification for data visualisation and transport planning"
description: "Robin Lovelace, Zhao Wang, Will Deakin, and Josiah Parry (2024). Reproducible methods for network simplification for data visualisation and transport planning. *32nd GISRUK Conference 2024*. https://doi.org/10.5281/zenodo.11077553"
date: "2024-04-11"
title-block-banner: false
toc: false
citation-key: "lovelace_reproducible_2024"
citation-type: "paper-conference"
citation-type-label: "Conference Paper"
venue: "32nd GISRUK Conference 2024"
doi: "10.5281/zenodo.11077553"
publication-url: "https://zenodo.org/records/11077553"
authors:
  - "Robin Lovelace"
  - "Zhao Wang"
  - "Will Deakin"
  - "Josiah Parry"
abstract: "Route network datasets, crucial to transport models, have grown complex, leading to visualization issues and potential misinterpretations. We address this by presenting two methods for simplifying these datasets: image skeletonization and Voronoi diagram-centreline identification. We have developed two packages, the “parenx” Python package (available on pip) and the “rnetmatch” R package (available on GitHub) to implement these methods. The approach has applications in transportation, demonstrated by their use in the publicly available Network Planning Tool funded by Transport for Scotland."
---

**Type:** Conference Paper
**Venue:** 32nd GISRUK Conference 2024
**Year:** 2024

[DOI](https://doi.org/10.5281/zenodo.11077553) [Publisher Link](https://zenodo.org/records/11077553) [BibTeX](entry.bib)

## Abstract

Route network datasets, crucial to transport models, have grown complex, leading to visualization issues and potential misinterpretations. We address this by presenting two methods for simplifying these datasets: image skeletonization and Voronoi diagram-centreline identification. We have developed two packages, the “parenx” Python package (available on pip) and the “rnetmatch” R package (available on GitHub) to implement these methods. The approach has applications in transportation, demonstrated by their use in the publicly available Network Planning Tool funded by Transport for Scotland.

## Citation

Robin Lovelace, Zhao Wang, Will Deakin, and Josiah Parry (2024). Reproducible methods for network simplification for data visualisation and transport planning. *32nd GISRUK Conference 2024*. https://doi.org/10.5281/zenodo.11077553

## BibTeX

```bibtex
@inproceedings{lovelace_reproducible_2024,
  title = {Reproducible Methods for Network Simplification for Data Visualisation and Transport Planning},
  booktitle = {32nd {{GISRUK Conference}} 2024},
  author = {Lovelace, Robin and Wang, Zhao and Deakin, Will and Parry, Josiah},
  date = {2024-04-11},
  publisher = {Zenodo},
  location = {Leeds},
  doi = {10.5281/zenodo.11077553},
  url = {https://zenodo.org/records/11077553},
  urldate = {2024-05-02},
  abstract = {Route network datasets, crucial to transport models, have grown complex, leading to visualization issues and potential misinterpretations. We address this by presenting two methods for simplifying these datasets: image skeletonization and Voronoi diagram-centreline identification. We have developed two packages, the ‘parenx’ Python package (available on pip) and the ‘rnetmatch’ R package (available on GitHub) to implement these methods. The approach has applications in transportation, demonstrated by their use in the publicly available Network Planning Tool funded by Transport for Scotland.},
  eventtitle = {{{GISRUK}}},
  file = {/home/robin/Zotero/storage/EZ475BRU/Lovelace et al. - 2024 - Reproducible methods for network simplification fo.pdf}
}
```

## Notes

{{< include _notes.qmd >}}
