---
title: "Socioeconomic inequalities in cycling safety: An analysis of cycling injury risk by residential deprivation level in England"
description: "Eugeni Vidal Tortosa, Robin Lovelace, Eva Heinen, and Richard P. Mann (2021). Socioeconomic inequalities in cycling safety: An analysis of cycling injury risk by residential deprivation level in England. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2021.101291"
date: "2021-12-01"
title-block-banner: false
toc: false
citation-key: "vidaltortosa_socioeconomic_2021"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Transport & Health"
doi: "10.1016/j.jth.2021.101291"
publication-url: "https://www.sciencedirect.com/science/article/pii/S2214140521003212"
authors:
  - "Eugeni Vidal Tortosa"
  - "Robin Lovelace"
  - "Eva Heinen"
  - "Richard P. Mann"
abstract: "Introduction Previous studies have found a positive association between cycling injury risk and residential deprivation. However, most of these studies focused on serious and fatal injuries, children, and a specific point in time. This study explores i) inequalities in cycling injury risk by residential deprivation for all recorded casualties (slight, serious, and fatal) in England, ii) whether these inequalities vary by sex and age, and iii) how they have changed over time. Methods Using the STATS19 database of road traffic casualties in Britain, the English National Travel Survey, and population estimates for England over the six-year period 2014–2019, we estimated the ratio of slight, serious, and fatal cycling casualties per billion kilometres cycled by residential Index of Multiple Deprivation (IMD) quintile; by residential IMD quintile and sex and age group; and by residential IMD quintile and year. Results We found that the higher the level of residential deprivation, the higher the slight and serious cycling injury risk. The fatal cycling injury risk was also higher in individuals from the most deprived areas. Inequalities were particularly large for children, with slight and serious rates three times higher for children from the most deprived areas than for children from the least deprived areas. We also found that the linear trend lines of the slight and serious injury rates between 2014 and 2019 declined in the least deprived quintiles but not in the most deprived quintiles, which suggests that inequalities in slight and serious cycling injuries may have grown over the last years. Conclusion This study found that people from deprived areas are at higher risk of cycling injury for all types of severity; that children from deprived areas are most at risk; and that these inequalities may have recently increased."
---

**Type:** Journal Article
**Venue:** Journal of Transport & Health
**Year:** 2021

[DOI](https://doi.org/10.1016/j.jth.2021.101291) [Publisher Link](https://www.sciencedirect.com/science/article/pii/S2214140521003212) [BibTeX](entry.bib)

## Abstract

Introduction Previous studies have found a positive association between cycling injury risk and residential deprivation. However, most of these studies focused on serious and fatal injuries, children, and a specific point in time. This study explores i) inequalities in cycling injury risk by residential deprivation for all recorded casualties (slight, serious, and fatal) in England, ii) whether these inequalities vary by sex and age, and iii) how they have changed over time. Methods Using the STATS19 database of road traffic casualties in Britain, the English National Travel Survey, and population estimates for England over the six-year period 2014–2019, we estimated the ratio of slight, serious, and fatal cycling casualties per billion kilometres cycled by residential Index of Multiple Deprivation (IMD) quintile; by residential IMD quintile and sex and age group; and by residential IMD quintile and year. Results We found that the higher the level of residential deprivation, the higher the slight and serious cycling injury risk. The fatal cycling injury risk was also higher in individuals from the most deprived areas. Inequalities were particularly large for children, with slight and serious rates three times higher for children from the most deprived areas than for children from the least deprived areas. We also found that the linear trend lines of the slight and serious injury rates between 2014 and 2019 declined in the least deprived quintiles but not in the most deprived quintiles, which suggests that inequalities in slight and serious cycling injuries may have grown over the last years. Conclusion This study found that people from deprived areas are at higher risk of cycling injury for all types of severity; that children from deprived areas are most at risk; and that these inequalities may have recently increased.

## Citation

Eugeni Vidal Tortosa, Robin Lovelace, Eva Heinen, and Richard P. Mann (2021). Socioeconomic inequalities in cycling safety: An analysis of cycling injury risk by residential deprivation level in England. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2021.101291

## BibTeX

```bibtex
@article{vidaltortosa_socioeconomic_2021,
	title = {Socioeconomic inequalities in cycling safety: {An} analysis of cycling injury risk by residential deprivation level in {England}},
	volume = {23},
	copyright = {Creative Commons Attribution-ShareAlike 4.0 International Licence (CC-BY-SA)},
	issn = {2214-1405},
	shorttitle = {Socioeconomic inequalities in cycling safety},
	url = {https://www.sciencedirect.com/science/article/pii/S2214140521003212},
	doi = {10.1016/j.jth.2021.101291},
	abstract = {Introduction
Previous studies have found a positive association between cycling injury risk and residential deprivation. However, most of these studies focused on serious and fatal injuries, children, and a specific point in time. This study explores i) inequalities in cycling injury risk by residential deprivation for all recorded casualties (slight, serious, and fatal) in England, ii) whether these inequalities vary by sex and age, and iii) how they have changed over time.
Methods
Using the STATS19 database of road traffic casualties in Britain, the English National Travel Survey, and population estimates for England over the six-year period 2014–2019, we estimated the ratio of slight, serious, and fatal cycling casualties per billion kilometres cycled by residential Index of Multiple Deprivation (IMD) quintile; by residential IMD quintile and sex and age group; and by residential IMD quintile and year.
Results
We found that the higher the level of residential deprivation, the higher the slight and serious cycling injury risk. The fatal cycling injury risk was also higher in individuals from the most deprived areas. Inequalities were particularly large for children, with slight and serious rates three times higher for children from the most deprived areas than for children from the least deprived areas. We also found that the linear trend lines of the slight and serious injury rates between 2014 and 2019 declined in the least deprived quintiles but not in the most deprived quintiles, which suggests that inequalities in slight and serious cycling injuries may have grown over the last years.
Conclusion
This study found that people from deprived areas are at higher risk of cycling injury for all types of severity; that children from deprived areas are most at risk; and that these inequalities may have recently increased.},
	language = {en},
	urldate = {2021-11-18},
	journal = {Journal of Transport \& Health},
	author = {Vidal Tortosa, Eugeni and Lovelace, Robin and Heinen, Eva and Mann, Richard P.},
	month = dec,
	year = {2021},
	keywords = {Cycling, Deprivation, Inequalities, Road traffic injury, Trends},
	pages = {101291},
}
```

## Notes

{{< include _notes.qmd >}}
