---
title: "Reproducible methods for modeling combined public transport and cycling trips and associated benefits: Evidence from the biclaR tool"
description: "Rosa Félix, Filipe Moura, and Robin Lovelace (2025). Reproducible methods for modeling combined public transport and cycling trips and associated benefits: Evidence from the biclaR tool. *Computers, Environment and Urban Systems*. https://doi.org/10.1016/j.compenvurbsys.2024.102230"
date: "2025-04-01"
title-block-banner: false
toc: false
citation-key: "felix_reproducible_2025"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Computers, Environment and Urban Systems"
doi: "10.1016/j.compenvurbsys.2024.102230"
publication-url: "https://www.sciencedirect.com/science/article/pii/S0198971524001595"
authors:
  - "Rosa Félix"
  - "Filipe Moura"
  - "Robin Lovelace"
abstract: "A high proportion of car trips can be replaced by a combination of public transit and cycling for the first-and-last mile. This paper estimates the potential for cycling combined with public transit as a substitute for car trips in the Lisbon metropolitan area and assesses its socio-environmental impacts using open data and open source tools. A decision support tool that facilitates the design and development of a metropolitan cycling network was developed (biclaR). The social and environmental impacts were assessed using Health World Organization tools. The impacts of shifting car trips to public transport were also estimated and monetized. The results show that 10 % of all trips could be made by cycling in combination with public transport. Shifting to cycling for the shorter first and last mile stages can reduce annual CO2eq emissions from 3000 to 7500 tons/day, while for the public transport leg, the transfer from car avoids of up to 20,500 tons of CO2eq emissions per year. The estimated socio-environmental benefits are of €125 million to €325 million over 10 years. This evidence can support policymakers to prioritize interventions that reduce the reliance on private motor vehicles."
---

**Type:** Journal Article
**Venue:** Computers, Environment and Urban Systems
**Year:** 2025

[DOI](https://doi.org/10.1016/j.compenvurbsys.2024.102230) [Publisher Link](https://www.sciencedirect.com/science/article/pii/S0198971524001595) [BibTeX](entry.bib)

## Abstract

A high proportion of car trips can be replaced by a combination of public transit and cycling for the first-and-last mile. This paper estimates the potential for cycling combined with public transit as a substitute for car trips in the Lisbon metropolitan area and assesses its socio-environmental impacts using open data and open source tools. A decision support tool that facilitates the design and development of a metropolitan cycling network was developed (biclaR). The social and environmental impacts were assessed using Health World Organization tools. The impacts of shifting car trips to public transport were also estimated and monetized. The results show that 10 % of all trips could be made by cycling in combination with public transport. Shifting to cycling for the shorter first and last mile stages can reduce annual CO2eq emissions from 3000 to 7500 tons/day, while for the public transport leg, the transfer from car avoids of up to 20,500 tons of CO2eq emissions per year. The estimated socio-environmental benefits are of €125 million to €325 million over 10 years. This evidence can support policymakers to prioritize interventions that reduce the reliance on private motor vehicles.

## Citation

Rosa Félix, Filipe Moura, and Robin Lovelace (2025). Reproducible methods for modeling combined public transport and cycling trips and associated benefits: Evidence from the biclaR tool. *Computers, Environment and Urban Systems*. https://doi.org/10.1016/j.compenvurbsys.2024.102230

## BibTeX

```bibtex
@article{felix_reproducible_2025,
  title = {Reproducible Methods for Modeling Combined Public Transport and Cycling Trips and Associated Benefits: {{Evidence}} from the {{biclaR}} Tool},
  shorttitle = {Reproducible Methods for Modeling Combined Public Transport and Cycling Trips and Associated Benefits},
  author = {Félix, Rosa and Moura, Filipe and Lovelace, Robin},
  date = {2025-04-01},
  journaltitle = {Computers, Environment and Urban Systems},
  shortjournal = {Computers, Environment and Urban Systems},
  volume = {117},
  pages = {102230},
  issn = {0198-9715},
  doi = {10.1016/j.compenvurbsys.2024.102230},
  url = {https://www.sciencedirect.com/science/article/pii/S0198971524001595},
  urldate = {2024-12-12},
  abstract = {A high proportion of car trips can be replaced by a combination of public transit and cycling for the first-and-last mile. This paper estimates the potential for cycling combined with public transit as a substitute for car trips in the Lisbon metropolitan area and assesses its socio-environmental impacts using open data and open source tools. A decision support tool that facilitates the design and development of a metropolitan cycling network was developed (biclaR). The social and environmental impacts were assessed using Health World Organization tools. The impacts of shifting car trips to public transport were also estimated and monetized. The results show that 10~\% of all trips could be made by cycling in combination with public transport. Shifting to cycling for the shorter first and last mile stages can reduce annual CO2eq emissions from 3000 to 7500 tons/day, while for the public transport leg, the transfer from car avoids of up to 20,500 tons of CO2eq emissions per year. The estimated socio-environmental benefits are of €125 million to €325 million over 10~years. This evidence can support policymakers to prioritize interventions that reduce the reliance on private motor vehicles.},
  keywords = {Active transport,Environmental impacts,First and last mile,Health economic assessment,Intermodality,Open data and methods},
  annotation = {0 citations (Crossref) [2024-12-13]},
  file = {/home/robin/Zotero/storage/H8SRRRPU/S0198971524001595.html}
}
```

## Notes

{{< include _notes.qmd >}}
