---
title: "Multivariate hierarchical analysis of car crashes data considering a spatial network lattice"
description: "Andrea Gilardi, Jorge Mateu, Riccardo Borgoni, and Robin Lovelace (2022). Multivariate hierarchical analysis of car crashes data considering a spatial network lattice. *Journal of the Royal Statistical Society: Series A (Statistics in Society)*. https://doi.org/10.1111/rssa.12823"
date: "2022-01-01"
title-block-banner: false
toc: false
citation-key: "gilardi_multivariate_2022a"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of the Royal Statistical Society: Series A (Statistics in Society)"
doi: "10.1111/rssa.12823"
publication-url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/rssa.12823"
authors:
  - "Andrea Gilardi"
  - "Jorge Mateu"
  - "Riccardo Borgoni"
  - "Robin Lovelace"
abstract: "Road traffic casualties represent a hidden global epidemic, demanding evidence-based interventions. This paper demonstrates a network lattice approach for identifying road segments of particular concern, based on a case study of a major city (Leeds, UK), in which 5862 crashes of different severities were recorded over an 8-year period (2011–2018). We consider a family of Bayesian hierarchical models that include spatially structured and unstructured random effects to capture the dependencies between the severity levels. Results highlight roads that are more prone to collisions, relative to estimated traffic volumes, in the north-west and south of city centre. We analyse the modifiable areal unit problem (MAUP), proposing a novel procedure to investigate the presence of MAUP on a network lattice. We conclude that our methods enable a reliable estimation of road safety levels to help identify “hotspots” on the road network and to inform effective local interventions."
---

**Type:** Journal Article
**Venue:** Journal of the Royal Statistical Society: Series A (Statistics in Society)
**Year:** 2022

[DOI](https://doi.org/10.1111/rssa.12823) [Publisher Link](https://onlinelibrary.wiley.com/doi/abs/10.1111/rssa.12823) [BibTeX](entry.bib)

## Abstract

Road traffic casualties represent a hidden global epidemic, demanding evidence-based interventions. This paper demonstrates a network lattice approach for identifying road segments of particular concern, based on a case study of a major city (Leeds, UK), in which 5862 crashes of different severities were recorded over an 8-year period (2011–2018). We consider a family of Bayesian hierarchical models that include spatially structured and unstructured random effects to capture the dependencies between the severity levels. Results highlight roads that are more prone to collisions, relative to estimated traffic volumes, in the north-west and south of city centre. We analyse the modifiable areal unit problem (MAUP), proposing a novel procedure to investigate the presence of MAUP on a network lattice. We conclude that our methods enable a reliable estimation of road safety levels to help identify “hotspots” on the road network and to inform effective local interventions.

## Citation

Andrea Gilardi, Jorge Mateu, Riccardo Borgoni, and Robin Lovelace (2022). Multivariate hierarchical analysis of car crashes data considering a spatial network lattice. *Journal of the Royal Statistical Society: Series A (Statistics in Society)*. https://doi.org/10.1111/rssa.12823

## BibTeX

```bibtex
@article{gilardi_multivariate_2022a,
	title = {Multivariate hierarchical analysis of car crashes data considering a spatial network lattice},
	volume = {185},
	copyright = {CC0 1.0 Universal Public Domain Dedication},
	issn = {1467-985X},
	url = {https://onlinelibrary.wiley.com/doi/abs/10.1111/rssa.12823},
	doi = {10.1111/rssa.12823},
	abstract = {Road traffic casualties represent a hidden global epidemic, demanding evidence-based interventions. This paper demonstrates a network lattice approach for identifying road segments of particular concern, based on a case study of a major city (Leeds, UK), in which 5862 crashes of different severities were recorded over an 8-year period (2011–2018). We consider a family of Bayesian hierarchical models that include spatially structured and unstructured random effects to capture the dependencies between the severity levels. Results highlight roads that are more prone to collisions, relative to estimated traffic volumes, in the north-west and south of city centre. We analyse the modifiable areal unit problem (MAUP), proposing a novel procedure to investigate the presence of MAUP on a network lattice. We conclude that our methods enable a reliable estimation of road safety levels to help identify ‘hotspots’ on the road network and to inform effective local interventions.},
	language = {en},
	number = {3},
	urldate = {2022-11-24},
	journal = {Journal of the Royal Statistical Society: Series A (Statistics in Society)},
	author = {Gilardi, Andrea and Mateu, Jorge and Borgoni, Riccardo and Lovelace, Robin},
	year = {2022},
	note = {\_eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1111/rssa.12823
tex.ids= gilardi\_multivariate\_2021
arXiv: 2011.12595},
	keywords = {Bayesian hierarchical models, MAUP, Statistics - Applications, car crashes data, multivariate modelling, network lattice, spatial networks},
	pages = {1150--1177},
}
```

## Notes

{{< include _notes.qmd >}}
