---
title: "Road lighting and cycling: A review of the academic literature and policy guidelines"
description: "Eugeni Vidal-Tortosa and Robin Lovelace (2023). Road lighting and cycling: A review of the academic literature and policy guidelines. *Journal of Cycling and Micromobility Research*. https://doi.org/10.1016/j.jcmr.2023.100008"
date: "2023-12-09"
title-block-banner: false
toc: false
citation-key: "vidal-tortosa_road_2023"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Cycling and Micromobility Research"
doi: "10.1016/j.jcmr.2023.100008"
publication-url: "https://www.sciencedirect.com/science/article/pii/S2950105923000086"
authors:
  - "Eugeni Vidal-Tortosa"
  - "Robin Lovelace"
abstract: "Many studies have explored the impact of macro and meso attributes of the built environment — such as population density, land use, proximity to services, and cycle infrastructure — on cycling. Less attention has been paid to micro attributes of the built environment. This paper reviews the academic literature on the relationship between road lighting and cycling, and identifies gaps to provide direction to future work. It also reviews policy guidelines on lighting and cycling infrastructure. Findings from the review of academic research show a clear positive effect of road lighting on cycling. The effect seems stronger among potential and less experienced cyclists. This suggests that investment in road lighting may be a cost-effective intervention to increase cycling and make it more inclusive. More empirical work is needed, including on the impact that lighting may have on different types of cyclists and cycling, the optimal lighting for cyclists, the cost-effectiveness of lighting interventions, and in developing countries and countries at extreme latitudes. There is also a need for research with higher geographic and temporal resolution, “before/after” approaches to explore changes over time, and accounting for other factors associated with cycling. Findings from the review of policy guidelines reveal that lighting in cycling infrastructure is increasingly being considered, not only for the safety of cyclists, but also to make utility cycling more appealing and accessible at night."
---

**Type:** Journal Article
**Venue:** Journal of Cycling and Micromobility Research
**Year:** 2023

[DOI](https://doi.org/10.1016/j.jcmr.2023.100008) [Publisher Link](https://www.sciencedirect.com/science/article/pii/S2950105923000086) [BibTeX](entry.bib)

## Abstract

Many studies have explored the impact of macro and meso attributes of the built environment — such as population density, land use, proximity to services, and cycle infrastructure — on cycling. Less attention has been paid to micro attributes of the built environment. This paper reviews the academic literature on the relationship between road lighting and cycling, and identifies gaps to provide direction to future work. It also reviews policy guidelines on lighting and cycling infrastructure. Findings from the review of academic research show a clear positive effect of road lighting on cycling. The effect seems stronger among potential and less experienced cyclists. This suggests that investment in road lighting may be a cost-effective intervention to increase cycling and make it more inclusive. More empirical work is needed, including on the impact that lighting may have on different types of cyclists and cycling, the optimal lighting for cyclists, the cost-effectiveness of lighting interventions, and in developing countries and countries at extreme latitudes. There is also a need for research with higher geographic and temporal resolution, “before/after” approaches to explore changes over time, and accounting for other factors associated with cycling. Findings from the review of policy guidelines reveal that lighting in cycling infrastructure is increasingly being considered, not only for the safety of cyclists, but also to make utility cycling more appealing and accessible at night.

## Citation

Eugeni Vidal-Tortosa and Robin Lovelace (2023). Road lighting and cycling: A review of the academic literature and policy guidelines. *Journal of Cycling and Micromobility Research*. https://doi.org/10.1016/j.jcmr.2023.100008

## BibTeX

```bibtex
@article{vidal-tortosa_road_2023,
  title = {Road Lighting and Cycling: {{A}} Review of the Academic Literature and Policy Guidelines},
  shorttitle = {Road Lighting and Cycling},
  author = {Vidal-Tortosa, Eugeni and Lovelace, Robin},
  date = {2023-12-09},
  journaltitle = {Journal of Cycling and Micromobility Research},
  shortjournal = {Journal of Cycling and Micromobility Research},
  pages = {100008},
  issn = {2950-1059},
  doi = {10.1016/j.jcmr.2023.100008},
  url = {https://www.sciencedirect.com/science/article/pii/S2950105923000086},
  urldate = {2023-12-12},
  abstract = {Many studies have explored the impact of macro and meso attributes of the built environment — such as population density, land use, proximity to services, and cycle infrastructure — on cycling. Less attention has been paid to micro attributes of the built environment. This paper reviews the academic literature on the relationship between road lighting and cycling, and identifies gaps to provide direction to future work. It also reviews policy guidelines on lighting and cycling infrastructure. Findings from the review of academic research show a clear positive effect of road lighting on cycling. The effect seems stronger among potential and less experienced cyclists. This suggests that investment in road lighting may be a cost-effective intervention to increase cycling and make it more inclusive. More empirical work is needed, including on the impact that lighting may have on different types of cyclists and cycling, the optimal lighting for cyclists, the cost-effectiveness of lighting interventions, and in developing countries and countries at extreme latitudes. There is also a need for research with higher geographic and temporal resolution, “before/after” approaches to explore changes over time, and accounting for other factors associated with cycling. Findings from the review of policy guidelines reveal that lighting in cycling infrastructure is increasingly being considered, not only for the safety of cyclists, but also to make utility cycling more appealing and accessible at night.},
  keywords = {Built environment,Crime,Cycling,Inclusivity,Road lighting,Road safety},
  annotation = {0 citations (Crossref) [2023-12-12]},
  file = {/home/robin/Zotero/storage/C96QSAUG/S2950105923000086.html}
}
```

## Notes

{{< include _notes.qmd >}}
