---
date: 2020-02-07
title: "Transport Data Science: from regional to street levels"
slug: tds-regional-workshop
---

### Invited seminar and workshop, [Université catholique de Louvain](https://uclouvain.be/en/index.html)

Hosted by [Christan Ritter](https://uclouvain.be/fr/repertoires/christian.ritter), this invited talk will take place at the [Institute of Statistics, Biostatistics and Actuarial Sciences](https://uclouvain.be/en/research-institutes/lidam/isba).

## Abstract

Data Science has emerged as an area of high and consistent growth in many sectors. High tech industries such as search engine optimisation, marketing and retail analytics have been quick to adopt new workflows. Transport has arguably been slow to adapt to the transformations towards open source software (as opposed to proprietary products that still dominate), command line and scriptable interfaces (unlike the graphical user interfaces of tools such as Excel) and code sharing and version development via platforms such as GitHub.

This talk demonstrates these new workflows, building on the [Transport chapter in the open source book Geocomputation with R](https://geocompr.robinlovelace.net/transport.html) and experience developing and deploying data science tools that are having a real world impact on transport policy and practice. It will provide insight into how multiple geographic scales of analysis were used to develop the [Propensity to Cycle Tool](http://www.pct.bike/), which Robin developed in collaboration with colleagues from 4 universities and which is being used by dozens of Local Authorities to develop strategic cycle networks. Furthermore, a live demo of the recently release [stats19](https://docs.ropensci.org/stats19/) package, which provides fast access to crash data for road safety research, will highlight the power of reproducibility and that transport data science is a practical field best discovered by doing it and collaboration using reproducible code.
