---
title: "Exploring the effect of local transport policies on the adoption of low emission vehicles: Evidence from the London Congestion Charge and Hybrid Electric Vehicles"
description: "Craig Morton, Robin Lovelace, and Jillian Anable (2017). Exploring the effect of local transport policies on the adoption of low emission vehicles: Evidence from the London Congestion Charge and Hybrid Electric Vehicles. *Transport Policy*. https://doi.org/10.1016/j.tranpol.2017.08.007"
date: "2017-11-01"
title-block-banner: false
toc: false
citation-key: "morton_exploring_2017"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Transport Policy"
doi: "10.1016/j.tranpol.2017.08.007"
publication-url: "http://www.sciencedirect.com/science/article/pii/S0967070X1730080X"
authors:
  - "Craig Morton"
  - "Robin Lovelace"
  - "Jillian Anable"
abstract: "The London Congestion Charge (LCC) is a transport policy with a precise spatial footprint. As such, its impact on the transport system can be expected to vary over space, providing an opportunity to explore the geographical reach of local transport interventions. This paper assesses whether the exemption of Hybrid Electric Vehicles (HEVs) from the LCC affected the registration rate of these vehicles in Greater London and the surrounding areas. The analysis uses official data on the number of HEVs registered across the local authorities of the United Kingdom. This dataset is assessed using [1] exploratory spatial analysis to determine the degree of spatial variation in HEV registrations, [2] area classifications to consider if HEV registrations diminish as nearness to the LCC recedes, and [3] spatial regression models to evaluate the association between distance to the LCC and HEV registrations, controlling for other area characteristics (i.e. socioeconomic, household, and transport system variables). The results clearly show that nearness to the LCC is positively associated with HEV registrations, implying that this form of transport policy is effective at promoting the adoption of low emission vehicles."
---

**Type:** Journal Article
**Venue:** Transport Policy
**Year:** 2017

[DOI](https://doi.org/10.1016/j.tranpol.2017.08.007) [Publisher Link](http://www.sciencedirect.com/science/article/pii/S0967070X1730080X) [BibTeX](entry.bib)

## Abstract

The London Congestion Charge (LCC) is a transport policy with a precise spatial footprint. As such, its impact on the transport system can be expected to vary over space, providing an opportunity to explore the geographical reach of local transport interventions. This paper assesses whether the exemption of Hybrid Electric Vehicles (HEVs) from the LCC affected the registration rate of these vehicles in Greater London and the surrounding areas. The analysis uses official data on the number of HEVs registered across the local authorities of the United Kingdom. This dataset is assessed using [1] exploratory spatial analysis to determine the degree of spatial variation in HEV registrations, [2] area classifications to consider if HEV registrations diminish as nearness to the LCC recedes, and [3] spatial regression models to evaluate the association between distance to the LCC and HEV registrations, controlling for other area characteristics (i.e. socioeconomic, household, and transport system variables). The results clearly show that nearness to the LCC is positively associated with HEV registrations, implying that this form of transport policy is effective at promoting the adoption of low emission vehicles.

## Citation

Craig Morton, Robin Lovelace, and Jillian Anable (2017). Exploring the effect of local transport policies on the adoption of low emission vehicles: Evidence from the London Congestion Charge and Hybrid Electric Vehicles. *Transport Policy*. https://doi.org/10.1016/j.tranpol.2017.08.007

## BibTeX

```bibtex
@article{morton_exploring_2017,
  title = {Exploring the Effect of Local Transport Policies on the Adoption of Low Emission Vehicles: {{Evidence}} from the {{London Congestion Charge}} and {{Hybrid Electric Vehicles}}},
  shorttitle = {Exploring the Effect of Local Transport Policies on the Adoption of Low Emission Vehicles},
  author = {Morton, Craig and Lovelace, Robin and Anable, Jillian},
  date = {2017-11-01},
  journaltitle = {Transport Policy},
  shortjournal = {Transport Policy},
  volume = {60},
  pages = {34--46},
  issn = {0967-070X},
  doi = {10.1016/j.tranpol.2017.08.007},
  url = {http://www.sciencedirect.com/science/article/pii/S0967070X1730080X},
  urldate = {2017-10-11},
  abstract = {The London Congestion Charge (LCC) is a transport policy with a precise spatial footprint. As such, its impact on the transport system can be expected to vary over space, providing an opportunity to explore the geographical reach of local transport interventions. This paper assesses whether the exemption of Hybrid Electric Vehicles (HEVs) from the LCC affected the registration rate of these vehicles in Greater London and the surrounding areas. The analysis uses official data on the number of HEVs registered across the local authorities of the United Kingdom. This dataset is assessed using [1] exploratory spatial analysis to determine the degree of spatial variation in HEV registrations, [2] area classifications to consider if HEV registrations diminish as nearness to the LCC recedes, and [3] spatial regression models to evaluate the association between distance to the LCC and HEV registrations, controlling for other area characteristics (i.e. socioeconomic, household, and transport system variables). The results clearly show that nearness to the LCC is positively associated with HEV registrations, implying that this form of transport policy is effective at promoting the adoption of low emission vehicles.},
  issue = {Supplement C},
  keywords = {Congestion charging,Hybrid Electric Vehicle demand,Local transport policy,Spatial diffusion},
  file = {/home/robin/Zotero/storage/ISFKK8BM/S0967070X1730080X.html}
}
```

## Notes

{{< include _notes.qmd >}}
