---
output: github_document
title: Four great things about UseR 2019
subtitle: A write-up from transport and geographic data research perspectives
---

UseR! is the highest profile and, I believe, most popular annual meeting for afficionados of R, the open source statistical programming language that has seen explosive growth since 'data science' became a buzzword.
Although I've been using R for around a decade, and heavily for around five years, [UseR! 2019](http://user2019.r-project.org/) was the first UseR! I attended.
I went with some preconceptions: I thought it would be like previous R events that I had attended, including the European R Users Meeting (ERUM) and SatRdays, but bigger.

It exceeded my expectations in many ways.
Despite only seeing part of it (I missed the tutorials on the Tuesday and the latter part of the final day on Friday), I learned many things from it.
Inspired by the 'useR aftRglow', I wrote some notes, some of which are worth sharing.
The organising committee of User2019 (hats off to you for an amazing event) has lessons for anyone thinking of putting on a successful event for research, software development, or anything aiming to encourage a friendly symposium vibe.
Here are some of the things that made it such an enlightening event.

# 1. Diverse formats

Sometimes going to events, and especially academic conferences (mentioning no names `*cough*` take note organisers of [AAAG](https://annualmeeting.aag.org/)/[RGS-IBG](https://www.rgs.org/research/annual-international-conference/) and other events with many presentation sessions), can feel undergoing 'death by powerpoint'.
A very slow, boring death.

UseR! was not like this at all.
Aside from the fact that many of presenters wouldn't *be seen dead* in front of PowerPoint slides, preferring instead more reproducible and flexible formats enabled by packages such as `xaringan` and `ioslides`, the diversity of formats and quality of the talks kept me on my toes in every session I attended.

The organisers had clearly given some thought to tackle this issue.
Instead of having only a couple of talk types (e.g. 15 minute presentation, 1 hour keynote) a range of formats were supported, including:

- Morning/afternoon tutorials, which took place on the Tuesday, allowing people to learn in depth about new methods/packages/approaches.
- A 'tidyverse development' day, which apparently involved physically taking issues and working on them in parallel, with a gong struck for every Pull Request accepted (this makes me wonder if the same technique can be used in other software ecosystems).
- Poster sessions, perhaps not an innovative thing in its own right, but at UseR! the poster showing event was preceded by Lightning Talks of ~1 minute each, so participants could identify which posters they would most like to visit.
- Lightning talk sessions, where participants had 5 minutes to convey the core message of their research.
These sessions were organised in themes and I chaired 'Applications and Methods' session, which contained some fascinating work.

There were still plenting of standard presentation sessions, but even in those sessions, the diversity kept things engaging.
Colin Gillespie went into stand-up comedy mode to deliver a vital message: that simple changes can improve the security of computer systems using R.
[Mine Çetinkaya-Rundel](https://en.wikipedia.org/wiki/Mine_%C3%87etinkaya-Rundel) used the metaphore of cooking to highlight the importance of digital learning environments for effective classrooms: would you rather cook in a unfinished kitchen or a complete one?
Use of a stable, in browser interface, as shown in the [Data Science in a Box](https://twitter.com/minebocek/status/1148904275550121984) project, can overcome the barrier of software installation to research, with clear implications for organisations: get a working instance of RStudio Server.

# 2. Diverse keynotes

There wasn't just one central 'keynote speaker' at the event but 6, half of whom were women, and with representatives from commercial, academic and non-profit organsiations.
The diversity of topics they covered was also impressive.
They ranged from Bettina Grün's highly technical yet accessible keynote on new models and packages for clustering data to Joe Cheng's talk on [shinymeta](https://github.com/rstudio/shinymeta).
It was rollercoaster ride to the publication of this just open-sourced package, which enables shiny apps to generate scripts underlying the dynamic results.
This could enable step change in the level of reproducibility of interactive web applications (vested interest: I'm the lead developer of the large shiny application, the [Propensity to Cycle Tool](http://www.pct.bike/) that would benefit from being more reproducible).

# 3. Videoing and dissemination

Not everyone has the time, energy or money to go to UseR!.
Some '[no fly pioneers](https://www.theguardian.com/travel/2019/may/22/could-you-give-up-flying-meet-the-no-plane-pioneers)' have given up flying to support global efforts to tackle the climate crisis.
I was very impressed to see acknowledgement of the conference's climate impacts, with a [form](https://enquetes.inra.fr/index.php/136679?lang=en) used to help calculate its carbon impact.

Whatever the reason, it is certain that the contents of UseR! will be of great interest to many more people than the ~2000 people who attended in person.
By recording and (eventually) releasing the videos of the talk, a much larger audience, into the millions, can be reached, as highlighted on the [website](http://user2019.r-project.org/):

> All talks will be recorded and all keynote sessions will be live streamed. Everything will be made avalaible on <a href="https://www.youtube.com/channel/UC_R5smHVXRYGhZYDJsnXTwg" target="_blank">R Consortium YouTube channel</a>. Thanks to R Consortium for supporting that initiative.

# 4. Relaxed atmosphere

The final great thing about UseR! 2019 was less objective but equally important: the social atmosphere.
The most reason why it had such a good vibe, I guess, was the attendees: in my experience R users, and people involved in the open source community in general, tend to friendly, humble and team-orientated.
Of course, this is how how conferences should be and many are, but I couldn't help notice a contrast between the humility of by 'big names' in the R community and the sense of self importance of some (albeit a small minority) high profile academics.

UseRs seem to have a great sense of humour and don't take themselves too seriously, which contributed to a friendly, inviting and non-hierarchical atmosphere.
This friendliness is self organising, but is also built into the constitution of UseR! in its [Code of Conduct](http://user2019.r-project.org/coc/).
Take note future conference organisers: it's easy to add a CoC and +s of doing so could be great.

The final reason for the relaxed atmosphere I noticed was more objective: all the equipment worked well, session chairs were well briefed on what they needed to and when, there were floating mics to allow clear questions from the audience, and the rooms were large enough such that at no point did I feel crammed into a session.
Furthermore, the arrangement and audio system of the rooms made it feel easy to change session, in case there were two talks in parallel sessions you really wanted to see.
Again, hats off to the organisers: it was VERY well organised.

# Other assorted notes and observations

## The host city of Toulouse

I really 


The map below...

## UseR! 2019 socials

I've often heard that the most valuable parts of conferences take place outside the formal sessions and there were ample opportunities for this to happen at UseR! 2019, with plentiful coffee breaks (and plentiful coffee!) and a range of fringe events and social events on a spectrum from the official Gala Dinner to spontaneous social trips to explore the night life in Toulouse.
The Gala Dinner was frankly amazing: it's not everyday that you get to explore and internation space station and listen to Flemanco music in the same evening (the photos below prove it is possible)!



## Catching up with collaborators

The event was a great opportunity to catch up with R collaborators.
Jakub Nowosad and I did some important thinking on our *Geocomputation with R* open source book (see the source code of his slides here).
And I finally managed to pursuade Colin Gillespie that we need to update our open source book *Efficient R Programming*. 
What this space.

## Serendipities

And of course there many serendities.
I had the honour of meeting many of my R heroes, who were all humble and friendly: it is possible to be high flying while humble.
On the train back I sat next R Core Team member Michael Meachler, and learned about the messages emitted every time packages such as `stplanr`, which depend on packages that use `R.oo`, are loaded:

```{r}
library(stplanr)
```

The only negative part of the conference for me was that it was too short.
Reflecting on it, I've decided to try to attend fewer conference but give them 100%, rather than attending many and feeling pressed for time.
"Quality over quantity" should be guiding principle of conference attendance I've decided.



<!-- I missed the train back home, the third time I've missed the Eurostar. -->
<!-- It's due to my habit of getting caught-up in the moment and simple poor calculation. -->
<!-- My train arrived in Paris Montparnasse at 16:13 giving me 2 hours before the train from Paris du Nord at 18:13. -->
<!-- It seems like ample time in which to make the walk, which Google calculated at around 2 hours. -->
<!-- For some reason I decided that the train departed at 18:48, meaning that I needed to be there by around 18:00. -->
<!-- If that were true I'd have got the train: I arrived at around 17:55. -->

<!-- In any case, the episode made me feel down. -->
<!-- I cursed myself for such bad timing, and getting lost in the moment. -->
<!-- But now I'm on the train home well fed and watered, and with support from my amazing fiancee Katy, I'm feeling better. -->
<!-- I don't have internet. -->
<!-- My reaction to this, constantly trying to connect, and checking my phone repeatedly, I think highlights a problem I have: I'm addicted to the quickfire feedback that the internet provides. -->
<!-- My attention span is too short. -->

<!-- But being away from the internet is also an opportunity, to write up the event, and shift to longer attention span activities. -->
<!-- I got some great photos from the event and want to do a write-up of it, especially the cycling part, that was awesome. -->
<!-- So I have a plan: comment out these three paragraphs and start over, with a write-up of #UseR2019 for public consumption, including the bike, my talk, meeting Michael Meachler and everthing. -->
<!-- A worthy use of time? -->
<!-- I cannot think a better one at the moment. -->
