---
title: "Jittering: A Computationally Efficient Method for Generating Realistic Route Networks from Origin-Destination Data"
description: "Robin Lovelace, Rosa Félix, and Dustin Carlino (2022). Jittering: A Computationally Efficient Method for Generating Realistic Route Networks from Origin-Destination Data. *Findings*. https://doi.org/10.32866/001c.33873"
date: "2022-04-08"
title-block-banner: false
toc: false
citation-key: "lovelace_jittering_2022b"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Findings"
doi: "10.32866/001c.33873"
publication-url: "https://findingspress.org/article/33873-jittering-a-computationally-efficient-method-for-generating-realistic-route-networks-from-origin-destination-data"
authors:
  - "Robin Lovelace"
  - "Rosa Félix"
  - "Dustin Carlino"
abstract: "Origin-destination (OD) datasets are often represented as “desire lines” between zone centroids. This paper presents a “jittering” approach to pre-processing and conversion of OD data into geographic desire lines that (1) samples unique origin and destination locations for each OD pair, and (2) splits “large” OD pairs into “sub-OD” pairs. Reproducible findings, based on the open source _odjitter_ Rust crate, show that route networks generated from jittered desire lines are more geographically diffuse than route networks generated by “unjittered” data. We conclude that the approach is a computationally efficient and flexible way to simulate transport patterns, particularly relevant for modelling active modes. Further work is needed to validate the approach and to find optimal settings for sampling and disaggregation."
---

**Type:** Journal Article
**Venue:** Findings
**Year:** 2022

[DOI](https://doi.org/10.32866/001c.33873) [Publisher Link](https://findingspress.org/article/33873-jittering-a-computationally-efficient-method-for-generating-realistic-route-networks-from-origin-destination-data) [BibTeX](entry.bib)

## Abstract

Origin-destination (OD) datasets are often represented as “desire lines” between zone centroids. This paper presents a “jittering” approach to pre-processing and conversion of OD data into geographic desire lines that (1) samples unique origin and destination locations for each OD pair, and (2) splits “large” OD pairs into “sub-OD” pairs. Reproducible findings, based on the open source _odjitter_ Rust crate, show that route networks generated from jittered desire lines are more geographically diffuse than route networks generated by “unjittered” data. We conclude that the approach is a computationally efficient and flexible way to simulate transport patterns, particularly relevant for modelling active modes. Further work is needed to validate the approach and to find optimal settings for sampling and disaggregation.

## Citation

Robin Lovelace, Rosa Félix, and Dustin Carlino (2022). Jittering: A Computationally Efficient Method for Generating Realistic Route Networks from Origin-Destination Data. *Findings*. https://doi.org/10.32866/001c.33873

## BibTeX

```bibtex
@article{lovelace_jittering_2022b,
  title = {Jittering: {{A Computationally Efficient Method}} for {{Generating Realistic Route Networks}} from {{Origin-Destination Data}}},
  shorttitle = {Jittering},
  author = {Lovelace, Robin and Félix, Rosa and Carlino, Dustin},
  date = {2022-04-08},
  journaltitle = {Findings},
  shortjournal = {Findings},
  pages = {33873},
  publisher = {Findings Press},
  doi = {10.32866/001c.33873},
  url = {https://findingspress.org/article/33873-jittering-a-computationally-efficient-method-for-generating-realistic-route-networks-from-origin-destination-data},
  urldate = {2022-05-05},
  abstract = {Origin-destination (OD) datasets are often represented as ‘desire lines’ between zone centroids. This paper presents a ‘jittering’ approach to pre-processing and conversion of OD data into geographic desire lines that (1) samples unique origin and destination locations for each OD pair, and (2) splits ‘large’ OD pairs into ‘sub-OD’ pairs. Reproducible findings, based on the open source \_odjitter\_ Rust crate, show that route networks generated from jittered desire lines are more geographically diffuse than route networks generated by ‘unjittered’ data. We conclude that the approach is a computationally efficient and flexible way to simulate transport patterns, particularly relevant for modelling active modes. Further work is needed to validate the approach and to find optimal settings for sampling and disaggregation.},
  langid = {english},
  file = {/home/robin/Zotero/storage/MW7B8GVG/Lovelace et al. - 2022 - Jittering A Computationally Efficient Method for .pdf;/home/robin/Zotero/storage/QZU3J666/33873-jittering-a-computationally-efficient-method-for-generating-realistic-route-networks-from.html}
}
```

## Notes

{{< include _notes.qmd >}}
