---
title: "Packaging code and data for reproducible research: A case study of journey time statistics"
description: "Federico Botta, Robin Lovelace, Laura Gilbert, and Arthur Turrell (2024). Packaging code and data for reproducible research: A case study of journey time statistics. *Environment and Planning B: Urban Analytics and City Science*. https://doi.org/10.1177/23998083241267331"
date: "2024-07-24"
title-block-banner: false
toc: false
citation-key: "botta_packaging_2024"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Environment and Planning B: Urban Analytics and City Science"
doi: "10.1177/23998083241267331"
publication-url: "https://doi.org/10.1177/23998083241267331"
authors:
  - "Federico Botta"
  - "Robin Lovelace"
  - "Laura Gilbert"
  - "Arthur Turrell"
abstract: "The effective and ethical use of data to inform decision-making offers huge value to the public sector, especially when delivered by transparent, reproducible, and robust data processing workflows. One way that governments are unlocking this value is through making their data publicly available, allowing more people and organisations to derive insights. However, open data is not enough in many cases: publicly available datasets need to be accessible in an analysis-ready form from popular data science tools, such as R and Python, for them to realise their full potential. This paper explores ways to maximise the impact of open data with reference to a case study of packaging code to facilitate reproducible analysis. We present the jtstats project, which consists of a main Python package, and a smaller R version, for importing, processing, and visualising large and complex datasets representing journey times, for many transport modes and trip purposes at multiple geographic levels, released by the UK Department for Transport (DfT). jtstats shows how domain specific packages can enable reproducible research within the public sector and beyond, saving duplicated effort and reducing the risks of errors from repeated analyses. We hope that the jtstats project inspires others, particularly those in the public sector, to add value to their data sets by making them more accessible."
---

**Type:** Journal Article
**Venue:** Environment and Planning B: Urban Analytics and City Science
**Year:** 2024

[DOI](https://doi.org/10.1177/23998083241267331) [URL](https://doi.org/10.1177/23998083241267331) [BibTeX](entry.bib)

## Abstract

The effective and ethical use of data to inform decision-making offers huge value to the public sector, especially when delivered by transparent, reproducible, and robust data processing workflows. One way that governments are unlocking this value is through making their data publicly available, allowing more people and organisations to derive insights. However, open data is not enough in many cases: publicly available datasets need to be accessible in an analysis-ready form from popular data science tools, such as R and Python, for them to realise their full potential. This paper explores ways to maximise the impact of open data with reference to a case study of packaging code to facilitate reproducible analysis. We present the jtstats project, which consists of a main Python package, and a smaller R version, for importing, processing, and visualising large and complex datasets representing journey times, for many transport modes and trip purposes at multiple geographic levels, released by the UK Department for Transport (DfT). jtstats shows how domain specific packages can enable reproducible research within the public sector and beyond, saving duplicated effort and reducing the risks of errors from repeated analyses. We hope that the jtstats project inspires others, particularly those in the public sector, to add value to their data sets by making them more accessible.

## Citation

Federico Botta, Robin Lovelace, Laura Gilbert, and Arthur Turrell (2024). Packaging code and data for reproducible research: A case study of journey time statistics. *Environment and Planning B: Urban Analytics and City Science*. https://doi.org/10.1177/23998083241267331

## BibTeX

```bibtex
@article{botta_packaging_2024,
  title = {Packaging Code and Data for Reproducible Research: {{A}} Case Study of Journey Time Statistics},
  shorttitle = {Packaging Code and Data for Reproducible Research},
  author = {Botta, Federico and Lovelace, Robin and Gilbert, Laura and Turrell, Arthur},
  date = {2024-07-24},
  journaltitle = {Environment and Planning B: Urban Analytics and City Science},
  pages = {23998083241267331},
  publisher = {SAGE Publications Ltd STM},
  issn = {2399-8083},
  doi = {10.1177/23998083241267331},
  url = {https://doi.org/10.1177/23998083241267331},
  urldate = {2024-07-25},
  abstract = {The effective and ethical use of data to inform decision-making offers huge value to the public sector, especially when delivered by transparent, reproducible, and robust data processing workflows. One way that governments are unlocking this value is through making their data publicly available, allowing more people and organisations to derive insights. However, open data is not enough in many cases: publicly available datasets need to be accessible in an analysis-ready form from popular data science tools, such as R and Python, for them to realise their full potential. This paper explores ways to maximise the impact of open data with reference to a case study of packaging code to facilitate reproducible analysis. We present the jtstats project, which consists of a main Python package, and a smaller R version, for importing, processing, and visualising large and complex datasets representing journey times, for many transport modes and trip purposes at multiple geographic levels, released by the UK Department for Transport (DfT). jtstats shows how domain specific packages can enable reproducible research within the public sector and beyond, saving duplicated effort and reducing the risks of errors from repeated analyses. We hope that the jtstats project inspires others, particularly those in the public sector, to add value to their data sets by making them more accessible.},
  langid = {english},
  annotation = {0 citations (Crossref) [2024-07-25]}
}
```

## Notes

{{< include _notes.qmd >}}
