---
title: New ways of working for a new generation of transport modellers
abstract: "Closing plenary: New ways of working for a new generation of transport modellers"
date: 2025-06-17 14:00:00+01:00
author: ["Robin Lovelace"]
---
I am looking forward to leading the closing plenary session at Modelling World 2025, which will be held from 17-18 June 2025 at the Manchester Conference Centre.

I'm chairing the final session of the conference, 15:45-17:00 on Wednesday 18th titled "New ways of working for a new generation of transport modellers".
In it we will hear from the following panelists about new tools and ways of working across generations:

- Robin North, CEO and Lead Technologist, Immense Simulations
- Raquel Sánchez, R&D Data Scientist, Nommon Solutions and Technologies
- James Hulse, Analyst, Transport for the North
- Francesca Bryden, Head of Data Engineering, Department for Transport
- Martin Campbell, Associate Director - Digital, SYSTRA
- Ian Williams, Independent Transport and Land Use Consultant

We will explore the evolving practices, tools, skills, and mindsets shaping the future of transport modelling.
More information about the conference can be found on the [official event website](https://www.modelling-world.com/conference-2025).

<!-- Social media:

Short version for Twitter:

I will be leading a plenary session at Modelling World 2025 in Manchester, discussing the evolving practices, tools, skills, and mindsets for the next generation of transport modellers. More info: https://www.modelling-world.com/conference-2025 #ModellingWorld2025 #TransportModelling

Longer version for LinkedIn:

I am excited to announce that I will be leading a plenary session at Modelling World 2025 in Manchester, where we will explore the evolving practices, tools, skills, and mindsets for the next generation of transport modellers. This session will address how the current generation of modellers needs to adapt, the role of AI in forecasting, the sufficiency of visualisation and data science, methods for evaluating model realism, and the importance of bold scenarios for substantial change. Join us for this insightful discussion! More info: https://www.modelling-world.com/conference-2025 #ModellingWorld2025 #TransportModelling

-->

