---
title: "Different people, different incentives? Examining the public acceptance of smartphone-based persuasive strategies for sustainable travel using psychographic segmentation"
description: "Rafael A. Reis, Susan Grant-Muller, Robin Lovelace, and Frances Hodgson (2020). Different people, different incentives? Examining the public acceptance of smartphone-based persuasive strategies for sustainable travel using psychographic segmentation. *International Journal of Sustainable Transportation*. https://doi.org/10.1080/15568318.2020.1836693"
date: "2020-11-15"
title-block-banner: false
toc: false
citation-key: "reis_different_2020"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "International Journal of Sustainable Transportation"
doi: "10.1080/15568318.2020.1836693"
publication-url: "https://doi.org/10.1080/15568318.2020.1836693"
authors:
  - "Rafael A. Reis"
  - "Susan Grant-Muller"
  - "Robin Lovelace"
  - "Frances Hodgson"
abstract: "The development and delivery of ICT-based persuasive strategies for the adoption of more environmental-friendly modes of transport is an emerging strategy to help tackle the problem of excessive use of individual Conventionally Fueled Vehicles (CFVs). The efficiency of this approach, like other information-based schemes, can benefit from the knowledge of which groups of individuals are more responsive to these types of interventions. The goal of this study is to examine the level of acceptability of persuasive schemes delivered using smartphone applications across different population segments. A cross-sectional survey was applied to 920 university students in Curitiba, a roughly 2-million inhabitant Brazilian city. The questionnaire was developed considering two groups of indicators: individual determinants of travel behavior, which were extracted from theories of social psychology (i.e. the Theory of Planned Behavior, the Norm-Activation Model and others), as well as stated intentions and attitudes toward a range of eleven different persuasive strategies (money or voucher rewards, points and rankings, social media sharing, etc.). Groups with different psychographic profiles were extracted from the sample using cluster and discriminant analyses. The acceptability of persuasive strategies were compared between segments. Results show a higher individual preference toward financial rewards and a relatively lower acceptability of social media tools. The acceptance level of groups that display higher control over the use of non-motorized forms of transport is higher than groups that are more psychologically predisposed to CFVs."
---

**Type:** Journal Article
**Venue:** International Journal of Sustainable Transportation
**Year:** 2020

[DOI](https://doi.org/10.1080/15568318.2020.1836693) [URL](https://doi.org/10.1080/15568318.2020.1836693) [BibTeX](entry.bib)

## Abstract

The development and delivery of ICT-based persuasive strategies for the adoption of more environmental-friendly modes of transport is an emerging strategy to help tackle the problem of excessive use of individual Conventionally Fueled Vehicles (CFVs). The efficiency of this approach, like other information-based schemes, can benefit from the knowledge of which groups of individuals are more responsive to these types of interventions. The goal of this study is to examine the level of acceptability of persuasive schemes delivered using smartphone applications across different population segments. A cross-sectional survey was applied to 920 university students in Curitiba, a roughly 2-million inhabitant Brazilian city. The questionnaire was developed considering two groups of indicators: individual determinants of travel behavior, which were extracted from theories of social psychology (i.e. the Theory of Planned Behavior, the Norm-Activation Model and others), as well as stated intentions and attitudes toward a range of eleven different persuasive strategies (money or voucher rewards, points and rankings, social media sharing, etc.). Groups with different psychographic profiles were extracted from the sample using cluster and discriminant analyses. The acceptability of persuasive strategies were compared between segments. Results show a higher individual preference toward financial rewards and a relatively lower acceptability of social media tools. The acceptance level of groups that display higher control over the use of non-motorized forms of transport is higher than groups that are more psychologically predisposed to CFVs.

## Citation

Rafael A. Reis, Susan Grant-Muller, Robin Lovelace, and Frances Hodgson (2020). Different people, different incentives? Examining the public acceptance of smartphone-based persuasive strategies for sustainable travel using psychographic segmentation. *International Journal of Sustainable Transportation*. https://doi.org/10.1080/15568318.2020.1836693

## BibTeX

```bibtex
@article{reis_different_2020,
  ids = {dosreis_different_2022},
  title = {Different People, Different Incentives? {{Examining}} the Public Acceptance of Smartphone-Based Persuasive Strategies for Sustainable Travel Using Psychographic Segmentation},
  shorttitle = {Different People, Different Incentives?},
  author = {family=Reis, given=Rafael A., prefix=dos, useprefix=false and Grant-Muller, Susan and Lovelace, Robin and Hodgson, Frances},
  date = {2020-11-15},
  journaltitle = {International Journal of Sustainable Transportation},
  volume = {0},
  number = {0},
  pages = {1--21},
  publisher = {Taylor \& Francis},
  issn = {1556-8318},
  doi = {10.1080/15568318.2020.1836693},
  url = {https://doi.org/10.1080/15568318.2020.1836693},
  urldate = {2020-11-15},
  abstract = {The development and delivery of ICT-based persuasive strategies for the adoption of more environmental-friendly modes of transport is an emerging strategy to help tackle the problem of excessive use of individual Conventionally Fueled Vehicles (CFVs). The efficiency of this approach, like other information-based schemes, can benefit from the knowledge of which groups of individuals are more responsive to these types of interventions. The goal of this study is to examine the level of acceptability of persuasive schemes delivered using smartphone applications across different population segments. A cross-sectional survey was applied to 920 university students in Curitiba, a roughly 2-million inhabitant Brazilian city. The questionnaire was developed considering two groups of indicators: individual determinants of travel behavior, which were extracted from theories of social psychology (i.e. the Theory of Planned Behavior, the Norm-Activation Model and others), as well as stated intentions and attitudes toward a range of eleven different persuasive strategies (money or voucher rewards, points and rankings, social media sharing, etc.). Groups with different psychographic profiles were extracted from the sample using cluster and discriminant analyses. The acceptability of persuasive strategies were compared between segments. Results show a higher individual preference toward financial rewards and a relatively lower acceptability of social media tools. The acceptance level of groups that display higher control over the use of non-motorized forms of transport is higher than groups that are more psychologically predisposed to CFVs.},
  keywords = {Market segmentation,persuasive strategies,positive incentives,public acceptability,travel behavior},
  file = {/home/robin/Zotero/storage/NZ47K5EJ/Reis et al. - 2020 - Different people, different incentives Examining .pdf;/home/robin/Zotero/storage/M8TQ8CFR/15568318.2020.html}
}
```

## Notes

{{< include _notes.qmd >}}
