---
title: "Evaluating the performance of Iterative Proportional Fitting for spatial microsimulation: New tests for an established technique"
description: "Robin Lovelace, Dimitris Ballas, Mark M. H. Birkin, Eveline Leeuwen, Dimitris Ballas, Eveline Leeuwen, and Mark M. H. Birkin (2015). Evaluating the performance of Iterative Proportional Fitting for spatial microsimulation: New tests for an established technique. *Journal of Artificial Societies and Social Simulation*."
date: "2015-03-01"
title-block-banner: false
toc: false
citation-key: "lovelace_evaluating_2015"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Artificial Societies and Social Simulation"
doi: ""
publication-url: "http://jasss.soc.surrey.ac.uk/18/2/21.html https://www.dropbox.com/s/szexnh80exjv3ov/ipfinr-jasss.pdf?dl=0"
authors:
  - "Robin Lovelace"
  - "Dimitris Ballas"
  - "Mark M. H. Birkin"
  - "Eveline Leeuwen"
  - "Dimitris Ballas"
  - "Eveline Leeuwen"
  - "Mark M. H. Birkin"
abstract: "Iterative Proportional Fitting (IPF), also known as biproportional fitting, “raking” or the RAS algorithm, is an established procedure used in a variety of applications across the social sciences. Primary amongst these for urban modelling has been its use in static spatial microsimulation to generate small area microdata — individual level data allocated to administrative zones. The technique is mature, widely used and relatively straight-forward. Although IPF is well described mathematically, accessible examples of the algorithm written in modern programming languages are rare. There is a tendency for researchers to “start from scratch”, resulting in a variety of ad hoc implementations and little evidence about the relative merits of differing approaches. These knowledge gaps mean that answers to certain methodological questions must be guessed: How can “empty cells” be identified and how do they influence model fit? Can IPF be made more computationally efficient? This paper tackles these questions and more using a systematic methodology with publicly available code and data. The results demonstrate the sensitivity of the results to initial conditions, notably the presence of “empty cells”, and the dramatic impact of software decisions on computational efficiency. The paper concludes by proposing an agenda for robust and transparent future tests in the field."
---

**Type:** Journal Article
**Venue:** Journal of Artificial Societies and Social Simulation
**Year:** 2015

[URL](http://jasss.soc.surrey.ac.uk/18/2/21.html https://www.dropbox.com/s/szexnh80exjv3ov/ipfinr-jasss.pdf?dl=0) [BibTeX](entry.bib)

## Abstract

Iterative Proportional Fitting (IPF), also known as biproportional fitting, “raking” or the RAS algorithm, is an established procedure used in a variety of applications across the social sciences. Primary amongst these for urban modelling has been its use in static spatial microsimulation to generate small area microdata — individual level data allocated to administrative zones. The technique is mature, widely used and relatively straight-forward. Although IPF is well described mathematically, accessible examples of the algorithm written in modern programming languages are rare. There is a tendency for researchers to “start from scratch”, resulting in a variety of ad hoc implementations and little evidence about the relative merits of differing approaches. These knowledge gaps mean that answers to certain methodological questions must be guessed: How can “empty cells” be identified and how do they influence model fit? Can IPF be made more computationally efficient? This paper tackles these questions and more using a systematic methodology with publicly available code and data. The results demonstrate the sensitivity of the results to initial conditions, notably the presence of “empty cells”, and the dramatic impact of software decisions on computational efficiency. The paper concludes by proposing an agenda for robust and transparent future tests in the field.

## Citation

Robin Lovelace, Dimitris Ballas, Mark M. H. Birkin, Eveline Leeuwen, Dimitris Ballas, Eveline Leeuwen, and Mark M. H. Birkin (2015). Evaluating the performance of Iterative Proportional Fitting for spatial microsimulation: New tests for an established technique. *Journal of Artificial Societies and Social Simulation*.

## BibTeX

```bibtex
@article{lovelace_evaluating_2015,
	title = {Evaluating the performance of {Iterative} {Proportional} {Fitting} for spatial microsimulation: new tests for an established technique},
	volume = {18},
	copyright = {CC0 1.0 Universal Public Domain Dedication},
	issn = {1460-7425},
	url = {http://jasss.soc.surrey.ac.uk/18/2/21.html https://www.dropbox.com/s/szexnh80exjv3ov/ipfinr-jasss.pdf?dl=0},
	abstract = {Iterative Proportional Fitting (IPF), also known as biproportional fitting, ‘raking’ or the RAS algorithm, is an established procedure used in a variety of applications across the social sciences. Primary amongst these for urban modelling has been its use in static spatial microsimulation to generate small area microdata — individual level data allocated to administrative zones. The technique is mature, widely used and relatively straight-forward. Although IPF is well described mathematically, accessible examples of the algorithm written in modern programming languages are rare. There is a tendency for researchers to ‘start from scratch’, resulting in a variety of ad hoc implementations and little evidence about the relative merits of differing approaches. These knowledge gaps mean that answers to certain methodological questions must be guessed: How can ‘empty cells’ be identified and how do they influence model fit? Can IPF be made more computationally efficient? This paper tackles these questions and more using a systematic methodology with publicly available code and data. The results demonstrate the sensitivity of the results to initial conditions, notably the presence of ‘empty cells’, and the dramatic impact of software decisions on computational efficiency. The paper concludes by proposing an agenda for robust and transparent future tests in the field.},
	number = {2},
	journal = {Journal of Artificial Societies and Social Simulation},
	author = {Lovelace, Robin and Ballas, Dimitris and Birkin, Mark M.H. and van Leeuwen, Eveline and Ballas, Dimitris and van Leeuwen, Eveline and Birkin, Mark M.H.},
	month = mar,
	year = {2015},
	keywords = {Deterministic Reweighting, Model Testing, Population Synthesis, Validation},
	pages = {21},
}
```

## Notes

{{< include _notes.qmd >}}
