---
title: "Is the London Cycle Hire Scheme becoming more inclusive? An evaluation of the shifting spatial distribution of uptake based on 70 million trips"
description: "Robin Lovelace, Roger Beecham, Eva Heinen, Eugeni Vidal Tortosa, Yuanxuan Yang, Chris Slade, and Antonia Roberts (2020). Is the London Cycle Hire Scheme becoming more inclusive? An evaluation of the shifting spatial distribution of uptake based on 70 million trips. *Transportation Research Part A: Policy and Practice*. https://doi.org/10.1016/j.tra.2020.07.017"
date: "2020-10-01"
title-block-banner: false
toc: false
citation-key: "lovelace_london_2020"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Transportation Research Part A: Policy and Practice"
doi: "10.1016/j.tra.2020.07.017"
publication-url: ""
authors:
  - "Robin Lovelace"
  - "Roger Beecham"
  - "Eva Heinen"
  - "Eugeni Vidal Tortosa"
  - "Yuanxuan Yang"
  - "Chris Slade"
  - "Antonia Roberts"
abstract: "Pro-cycling interventions, and cycle hire schemes in particular, are often assumed to primarily benefit the privileged. This framing has played-out in academic research, with many papers exploring the relationship between cycling and existing inequalities. A growing body of evidence suggests that cycle hire schemes tend to serve wealthy areas and young, high income groups, mirroring inequalities in other types of cycling uptake, yet there has been little research into the “direction of travel” and whether such inequalities are growing or “levelling up” over time. This paper explores the uptake of the London Cycle Hire Scheme (LCHS), a large, early and prominent scheme that had the explicit aim of “normalising” cycling. The method involved reproducible analysis (with code documented in the GitHub repo Robinlovelace/cycle-hire-inclusive) of 73.4 million cycle high records spanning 8 years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. The method involved analysis of 73.4 million cycle high records spanning 8 years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. We found that, contrary to the trend for increasing segregation and geographic inequalities, the usage of the LCHS have become increasingly geographically distributed across London over time, with AM peak usage in comparatively low-income areas seeing high levels of growth. Our study shows that cycle hire schemes can be designed and expanded in ways that benefit a wide range of people, including those from low income areas, and that new cycle hire docking stations in poorer areas can succeed."
---

**Type:** Journal Article
**Venue:** Transportation Research Part A: Policy and Practice
**Year:** 2020

[DOI](https://doi.org/10.1016/j.tra.2020.07.017) [BibTeX](entry.bib)

## Abstract

Pro-cycling interventions, and cycle hire schemes in particular, are often assumed to primarily benefit the privileged. This framing has played-out in academic research, with many papers exploring the relationship between cycling and existing inequalities. A growing body of evidence suggests that cycle hire schemes tend to serve wealthy areas and young, high income groups, mirroring inequalities in other types of cycling uptake, yet there has been little research into the “direction of travel” and whether such inequalities are growing or “levelling up” over time. This paper explores the uptake of the London Cycle Hire Scheme (LCHS), a large, early and prominent scheme that had the explicit aim of “normalising” cycling. The method involved reproducible analysis (with code documented in the GitHub repo Robinlovelace/cycle-hire-inclusive) of 73.4 million cycle high records spanning 8 years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. The method involved analysis of 73.4 million cycle high records spanning 8 years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. We found that, contrary to the trend for increasing segregation and geographic inequalities, the usage of the LCHS have become increasingly geographically distributed across London over time, with AM peak usage in comparatively low-income areas seeing high levels of growth. Our study shows that cycle hire schemes can be designed and expanded in ways that benefit a wide range of people, including those from low income areas, and that new cycle hire docking stations in poorer areas can succeed.

## Citation

Robin Lovelace, Roger Beecham, Eva Heinen, Eugeni Vidal Tortosa, Yuanxuan Yang, Chris Slade, and Antonia Roberts (2020). Is the London Cycle Hire Scheme becoming more inclusive? An evaluation of the shifting spatial distribution of uptake based on 70 million trips. *Transportation Research Part A: Policy and Practice*. https://doi.org/10.1016/j.tra.2020.07.017

## BibTeX

```bibtex
@article{lovelace_london_2020,
  title = {Is the {{London Cycle Hire Scheme}} Becoming More Inclusive? {{An}} Evaluation of the Shifting Spatial Distribution of Uptake Based on 70 Million Trips},
  shorttitle = {Is the {{London Cycle Hire Scheme}} Becoming More Inclusive?},
  author = {Lovelace, Robin and Beecham, Roger and Heinen, Eva and Vidal Tortosa, Eugeni and Yang, Yuanxuan and Slade, Chris and Roberts, Antonia},
  year = {2020},
  month = oct,
  journal = {Transportation Research Part A: Policy and Practice},
  volume = {140},
  pages = {1--15},
  issn = {0965-8564},
  doi = {10.1016/j.tra.2020.07.017},
  urldate = {2020-09-14},
  abstract = {Pro-cycling interventions, and cycle hire schemes in particular, are often assumed to primarily benefit the privileged. This framing has played-out in academic research, with many papers exploring the relationship between cycling and existing inequalities. A growing body of evidence suggests that cycle hire schemes tend to serve wealthy areas and young, high income groups, mirroring inequalities in other types of cycling uptake, yet there has been little research into the `direction of travel' and whether such inequalities are growing or `levelling up' over time. This paper explores the uptake of the London Cycle Hire Scheme (LCHS), a large, early and prominent scheme that had the explicit aim of `normalising' cycling. The method involved reproducible analysis (with code documented in the GitHub repo Robinlovelace/cycle-hire-inclusive) of 73.4 million cycle high records spanning 8~years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. The method involved analysis of 73.4 million cycle high records spanning 8~years from January 2012 to December 2019, using the geographic location of docking stations alongside official statistics to assess social and spatial inequalities in uptake. We found that, contrary to the trend for increasing segregation and geographic inequalities, the usage of the LCHS have become increasingly geographically distributed across London over time, with AM peak usage in comparatively low-income areas seeing high levels of growth. Our study shows that cycle hire schemes can be designed and expanded in ways that benefit a wide range of people, including those from low income areas, and that new cycle hire docking stations in poorer areas can succeed.},
  copyright = {CC0 1.0 Universal Public Domain Dedication},
  langid = {english},
  keywords = {Big data,Bikeshare,Cycle hire,Reproducible data science,Transport equity},
  file = {/home/robin/Zotero/storage/37HJ9EUF/Lovelace et al. - 2020 - Is the London Cycle Hire Scheme becoming more incl.pdf;/home/robin/Zotero/storage/JU8GR8MI/S0965856420306728.html}
}
```

## Notes

{{< include _notes.qmd >}}
