---
title: "Open access transport models: A leverage point in sustainable transport planning"
description: "Robin Lovelace, John Parkin, and Tom Cohen (2020). Open access transport models: A leverage point in sustainable transport planning. *Transport Policy*. https://doi.org/10.1016/j.tranpol.2020.06.015"
date: "2020-10-01"
title-block-banner: false
toc: false
citation-key: "lovelace_open_2020"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Transport Policy"
doi: "10.1016/j.tranpol.2020.06.015"
publication-url: "http://www.sciencedirect.com/science/article/pii/S0967070X19302781"
authors:
  - "Robin Lovelace"
  - "John Parkin"
  - "Tom Cohen"
abstract: "A large and growing body of evidence suggests fundamental changes are needed in transport systems, to tackle issues such as air pollution, physical inactivity and climate change. Transport models can play a major role in tackling these issues through the transport planning process, but they have historically been focussed on motorised modes (especially cars) and available only to professional transport planners working within the existing paradigm. Building on the principles of open access software, first developed in the context of geographic information systems, this paper develops and discusses the concept of open access transport models, which we define as models that are both developed using open source software and are available to be used by the public without the need for specialist training or the purchase of software licences. We explore the future potential of open access transport models to support the transition away from fossil fuels in the transport sector. We do this with reference to the literature on the use of tools in the planning process, and by exploring an example that is already in use: the “Propensity to Cycle Tool”. We conclude that open access transport models can be a leverage point in the planning process due to their ability to provide robust, transparent and actionable evidence that is available to a range of stakeholders, not just professional transport planners. Open access transport models represent a disruptive technology deserving further research and development, by planners, researchers and citizen scientists, including open source software developers and advocacy groups but, in order to fulfil their potential, they will require both financial and policy support from government bodies."
---

**Type:** Journal Article
**Venue:** Transport Policy
**Year:** 2020

[DOI](https://doi.org/10.1016/j.tranpol.2020.06.015) [Publisher Link](http://www.sciencedirect.com/science/article/pii/S0967070X19302781) [BibTeX](entry.bib)

## Abstract

A large and growing body of evidence suggests fundamental changes are needed in transport systems, to tackle issues such as air pollution, physical inactivity and climate change. Transport models can play a major role in tackling these issues through the transport planning process, but they have historically been focussed on motorised modes (especially cars) and available only to professional transport planners working within the existing paradigm. Building on the principles of open access software, first developed in the context of geographic information systems, this paper develops and discusses the concept of open access transport models, which we define as models that are both developed using open source software and are available to be used by the public without the need for specialist training or the purchase of software licences. We explore the future potential of open access transport models to support the transition away from fossil fuels in the transport sector. We do this with reference to the literature on the use of tools in the planning process, and by exploring an example that is already in use: the “Propensity to Cycle Tool”. We conclude that open access transport models can be a leverage point in the planning process due to their ability to provide robust, transparent and actionable evidence that is available to a range of stakeholders, not just professional transport planners. Open access transport models represent a disruptive technology deserving further research and development, by planners, researchers and citizen scientists, including open source software developers and advocacy groups but, in order to fulfil their potential, they will require both financial and policy support from government bodies.

## Citation

Robin Lovelace, John Parkin, and Tom Cohen (2020). Open access transport models: A leverage point in sustainable transport planning. *Transport Policy*. https://doi.org/10.1016/j.tranpol.2020.06.015

## BibTeX

```bibtex
@article{lovelace_open_2020,
  ids = {lovelace_open_2020a},
  title = {Open Access Transport Models: {{A}} Leverage Point in Sustainable Transport Planning},
  shorttitle = {Open Access Transport Models},
  author = {Lovelace, Robin and Parkin, John and Cohen, Tom},
  date = {2020-10-01},
  journaltitle = {Transport Policy},
  shortjournal = {Transport Policy},
  volume = {97},
  pages = {47--54},
  issn = {0967-070X},
  doi = {10.1016/j.tranpol.2020.06.015},
  url = {http://www.sciencedirect.com/science/article/pii/S0967070X19302781},
  urldate = {2020-08-04},
  abstract = {A large and growing body of evidence suggests fundamental changes are needed in transport systems, to tackle issues such as air pollution, physical inactivity and climate change. Transport models can play a major role in tackling these issues through the transport planning process, but they have historically been focussed on motorised modes (especially cars) and available only to professional transport planners working within the existing paradigm. Building on the principles of open access software, first developed in the context of geographic information systems, this paper develops and discusses the concept of open access transport models, which we define as models that are both developed using open source software and are available to be used by the public without the need for specialist training or the purchase of software licences. We explore the future potential of open access transport models to support the transition away from fossil fuels in the transport sector. We do this with reference to the literature on the use of tools in the planning process, and by exploring an example that is already in use: the ‘Propensity to Cycle Tool’. We conclude that open access transport models can be a leverage point in the planning process due to their ability to provide robust, transparent and actionable evidence that is available to a range of stakeholders, not just professional transport planners. Open access transport models represent a disruptive technology deserving further research and development, by planners, researchers and citizen scientists, including open source software developers and advocacy groups but, in order to fulfil their potential, they will require both financial and policy support from government bodies.},
  langid = {english},
  keywords = {Accessible models,Cycling,Demand modelling,Open access data,Open access models,Open access software,Sustainable transport,Transport planning},
  file = {/home/robin/Zotero/storage/MNB2VCS6/Lovelace et al. - 2020 - Open access transport models A leverage point in .pdf;/home/robin/Zotero/storage/VPTJXKA6/Lovelace et al. - 2020 - Open access transport models A leverage point in .pdf;/home/robin/Zotero/storage/9TKN7ZXD/S0967070X19302781.html;/home/robin/Zotero/storage/MJ3A6X2A/S0967070X19302781.html}
}
```

## Notes

{{< include _notes.qmd >}}
