---
title: The Active Travel Infrastructure Platform (ATIP)​
date: 2023-05-24 10:45:00+01:00
author: ["Robin Lovelace"]
---
# Abstract

ATIP is an open source web app initially developed in early 2023 to enable local transport 
planners to document, store and share geographic data on planned interventions. As of May 
2023 ATIP provides an intuitive interface to quickly sketch the location of a wide range of 
interventions including:

- Linear infrastructure, including new routes, pavement widening and road diets projects
- Crossings, including new pelican, zebra and other types of crossings
- Area-wide traffic management schemes, including modal filters and boundaries

Users can also add describe their planned schemes with free test or ATE's taxonomy (in 
progress). ATIP is designed for ease-of-use. It makes drawing lines and polygons snapped to 
existing streets and paths easy with 'route snapper' functionality, a world first for polygons.
The talk will outline the thinking behind ATIP, how it's been used in ATE to collect, for the first 
time, detailed geographic data on schemes, and the roadmap towards ATIP becoming a one 
stop shop for active travel infrastructure nationwide. ATIP. Finally, the talk will cover the 
technology powering ATIP, including Svelte, MapLibre GL, Rust, WebAssembly, and 
OpenStreetMap and how to harness these tools for other projects.

