---
title: "Scenarios of cycling to school in England, and associated health and carbon impacts: Application of the “Propensity to Cycle Tool”"
description: "Anna Goodman, Ilan Fridman Rojas, James Woodcock, Rachel Aldred, Nikolai Berkoff, Malcolm Morgan, Ali Abbas, and Robin Lovelace (2019). Scenarios of cycling to school in England, and associated health and carbon impacts: Application of the “Propensity to Cycle Tool”. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2019.01.008"
date: "2019-03-01"
title-block-banner: false
toc: false
citation-key: "goodman_scenarios_2019"
citation-type: "article-journal"
citation-type-label: "Journal Article"
venue: "Journal of Transport & Health"
doi: "10.1016/j.jth.2019.01.008"
publication-url: "http://www.sciencedirect.com/science/article/pii/S2214140518301257"
authors:
  - "Anna Goodman"
  - "Ilan Fridman Rojas"
  - "James Woodcock"
  - "Rachel Aldred"
  - "Nikolai Berkoff"
  - "Malcolm Morgan"
  - "Ali Abbas"
  - "Robin Lovelace"
abstract: "Background The Propensity to Cycle Tool (PCT) is a freely available, interactive tool help prioritise cycling initially launched in England in 2017 and based on adult commuting data. This paper applies the method to travel to school data, and assesses health and carbon benefits based on nationwide scenarios of cycling uptake. Methods The 2011 National School Census provides origin-destination data for all state-funded schools in England (N = 7,442,532 children aged 2–18 in 21,443 schools). Using this dataset, we modelled propensity to cycle as a function of route distance and hilliness between home and school. We generated scenarios, including “Go Dutch” – in which English children were as likely to cycle as Dutch children, accounting for trip distance and hilliness. We estimated changes in the level of cycling, walking, and driving, and associated impacts on physical activity and carbon emissions. Results In 2011, 1.8% of children cycled to school (1.0% in primary school, 2.7% in secondary school). If Dutch levels of cycling were reached, under the Go Dutch scenario, this would rise to 41.0%, a 22-fold increase. This is larger than the 6-fold increase in Go Dutch for adult commuting. This would increase total physical activity among pupils by 57%, and reduce transport-related carbon emissions by 81 kilotonnes/year. These impacts would be substantially larger in secondary schools than primary schools (a 96% vs. 9% increase in physical activity, respectively). Conclusion Cycling to school is uncommon in England compared with other Northern European countries. Trip distances and hilliness alone cannot explain the difference, suggesting substantial unmet potential. We show that policies resulting in substantial uptake of cycling to school would have important health and environmental benefits. At the level of road networks, the results can inform local investment in safe routes to school to help realise these potential benefits."
---

**Type:** Journal Article
**Venue:** Journal of Transport & Health
**Year:** 2019

[DOI](https://doi.org/10.1016/j.jth.2019.01.008) [Publisher Link](http://www.sciencedirect.com/science/article/pii/S2214140518301257) [BibTeX](entry.bib)

## Abstract

Background The Propensity to Cycle Tool (PCT) is a freely available, interactive tool help prioritise cycling initially launched in England in 2017 and based on adult commuting data. This paper applies the method to travel to school data, and assesses health and carbon benefits based on nationwide scenarios of cycling uptake. Methods The 2011 National School Census provides origin-destination data for all state-funded schools in England (N = 7,442,532 children aged 2–18 in 21,443 schools). Using this dataset, we modelled propensity to cycle as a function of route distance and hilliness between home and school. We generated scenarios, including “Go Dutch” – in which English children were as likely to cycle as Dutch children, accounting for trip distance and hilliness. We estimated changes in the level of cycling, walking, and driving, and associated impacts on physical activity and carbon emissions. Results In 2011, 1.8% of children cycled to school (1.0% in primary school, 2.7% in secondary school). If Dutch levels of cycling were reached, under the Go Dutch scenario, this would rise to 41.0%, a 22-fold increase. This is larger than the 6-fold increase in Go Dutch for adult commuting. This would increase total physical activity among pupils by 57%, and reduce transport-related carbon emissions by 81 kilotonnes/year. These impacts would be substantially larger in secondary schools than primary schools (a 96% vs. 9% increase in physical activity, respectively). Conclusion Cycling to school is uncommon in England compared with other Northern European countries. Trip distances and hilliness alone cannot explain the difference, suggesting substantial unmet potential. We show that policies resulting in substantial uptake of cycling to school would have important health and environmental benefits. At the level of road networks, the results can inform local investment in safe routes to school to help realise these potential benefits.

## Citation

Anna Goodman, Ilan Fridman Rojas, James Woodcock, Rachel Aldred, Nikolai Berkoff, Malcolm Morgan, Ali Abbas, and Robin Lovelace (2019). Scenarios of cycling to school in England, and associated health and carbon impacts: Application of the “Propensity to Cycle Tool”. *Journal of Transport & Health*. https://doi.org/10.1016/j.jth.2019.01.008

## BibTeX

```bibtex
@article{goodman_scenarios_2019,
	title = {Scenarios of cycling to school in {England}, and associated health and carbon impacts: {Application} of the ‘{Propensity} to {Cycle} {Tool}’},
	volume = {12},
	copyright = {CC0 1.0 Universal Public Domain Dedication},
	issn = {2214-1405},
	shorttitle = {Scenarios of cycling to school in {England}, and associated health and carbon impacts},
	url = {http://www.sciencedirect.com/science/article/pii/S2214140518301257},
	doi = {10.1016/j.jth.2019.01.008},
	abstract = {Background
The Propensity to Cycle Tool (PCT) is a freely available, interactive tool help prioritise cycling initially launched in England in 2017 and based on adult commuting data. This paper applies the method to travel to school data, and assesses health and carbon benefits based on nationwide scenarios of cycling uptake.
Methods
The 2011 National School Census provides origin-destination data for all state-funded schools in England (N = 7,442,532 children aged 2–18 in 21,443 schools). Using this dataset, we modelled propensity to cycle as a function of route distance and hilliness between home and school. We generated scenarios, including ‘Go Dutch’ – in which English children were as likely to cycle as Dutch children, accounting for trip distance and hilliness. We estimated changes in the level of cycling, walking, and driving, and associated impacts on physical activity and carbon emissions.
Results
In 2011, 1.8\% of children cycled to school (1.0\% in primary school, 2.7\% in secondary school). If Dutch levels of cycling were reached, under the Go Dutch scenario, this would rise to 41.0\%, a 22-fold increase. This is larger than the 6-fold increase in Go Dutch for adult commuting. This would increase total physical activity among pupils by 57\%, and reduce transport-related carbon emissions by 81 kilotonnes/year. These impacts would be substantially larger in secondary schools than primary schools (a 96\% vs. 9\% increase in physical activity, respectively).
Conclusion
Cycling to school is uncommon in England compared with other Northern European countries. Trip distances and hilliness alone cannot explain the difference, suggesting substantial unmet potential. We show that policies resulting in substantial uptake of cycling to school would have important health and environmental benefits. At the level of road networks, the results can inform local investment in safe routes to school to help realise these potential benefits.},
	urldate = {2019-03-04},
	journal = {Journal of Transport \& Health},
	author = {Goodman, Anna and Rojas, Ilan Fridman and Woodcock, James and Aldred, Rachel and Berkoff, Nikolai and Morgan, Malcolm and Abbas, Ali and Lovelace, Robin},
	month = mar,
	year = {2019},
	keywords = {Active travel, Carbon emissions, Cycling, Modelling, Physical activity, School},
	pages = {263--278},
}
```

## Notes

{{< include _notes.qmd >}}
