---
title: "A/B Street"
description: "Dustin Carlino, Yuwen Li, Michael Kirk, Mateusz Konieczny, Gedalia Kott, Bruce, Javed Nissar, Trevor Nederlof, Vinzent Steinberg, Robin Lovelace, Marcel Dejean, Orestis, Rémi Lauzier, Sam, Andrew Wei, Brian Lewis, Christopher Schmidt, Dmitriy Serdyuk, Filip Czaplicki, Fullstop000, Jeff Raymakers, Jeremias Volker, Kyle Huston, Lorenz Schmid, Max Shenfield, Nick Schimek, Tim Newsome, Tobias, Andi, and moo (2022). A/B Street. *Zenodo*. https://doi.org/10.5281/zenodo.6331922"
date: "2022-03-01"
title-block-banner: false
toc: false
citation-key: "abstreet_2022"
citation-type: ""
citation-type-label: ""
venue: "Zenodo"
doi: "10.5281/zenodo.6331922"
publication-url: "https://zenodo.org/record/6331922"
authors:
  - "Dustin Carlino"
  - "Yuwen Li"
  - "Michael Kirk"
  - "Mateusz Konieczny"
  - "Gedalia Kott"
  - "Bruce"
  - "Javed Nissar"
  - "Trevor Nederlof"
  - "Vinzent Steinberg"
  - "Robin Lovelace"
  - "Marcel Dejean"
  - "Orestis"
  - "Rémi Lauzier"
  - "Sam"
  - "Andrew Wei"
  - "Brian Lewis"
  - "Christopher Schmidt"
  - "Dmitriy Serdyuk"
  - "Filip Czaplicki"
  - "Fullstop000"
  - "Jeff Raymakers"
  - "Jeremias Volker"
  - "Kyle Huston"
  - "Lorenz Schmid"
  - "Max Shenfield"
  - "Nick Schimek"
  - "Tim Newsome"
  - "Tobias"
  - "Andi"
  - "moo"
abstract: "overhaul the rat-run mode: tighten up things counting as shortcuts, keep the same path after adding a filter change the LTN route planning tool to be map-wide, not per-neighborhood place filters at non 4-way intersections shrink some cases of overlapping roads, improving geometry when OSM data is not great a first round of simplifying LTN panels when the LTN blockfinding would’ve crashed previously, just fallback to using more expensive blockfinding bugfix: detect existing filters on really short roads fix initial camera placement outside of the main A/B Street app"
---

**Type:** 
**Venue:** Zenodo
**Year:** 2022

[DOI](https://doi.org/10.5281/zenodo.6331922) [Publisher Link](https://zenodo.org/record/6331922) [BibTeX](entry.bib)

## Abstract

overhaul the rat-run mode: tighten up things counting as shortcuts, keep the same path after adding a filter change the LTN route planning tool to be map-wide, not per-neighborhood place filters at non 4-way intersections shrink some cases of overlapping roads, improving geometry when OSM data is not great a first round of simplifying LTN panels when the LTN blockfinding would’ve crashed previously, just fallback to using more expensive blockfinding bugfix: detect existing filters on really short roads fix initial camera placement outside of the main A/B Street app

## Citation

Dustin Carlino, Yuwen Li, Michael Kirk, Mateusz Konieczny, Gedalia Kott, Bruce, Javed Nissar, Trevor Nederlof, Vinzent Steinberg, Robin Lovelace, Marcel Dejean, Orestis, Rémi Lauzier, Sam, Andrew Wei, Brian Lewis, Christopher Schmidt, Dmitriy Serdyuk, Filip Czaplicki, Fullstop000, Jeff Raymakers, Jeremias Volker, Kyle Huston, Lorenz Schmid, Max Shenfield, Nick Schimek, Tim Newsome, Tobias, Andi, and moo (2022). A/B Street. *Zenodo*. https://doi.org/10.5281/zenodo.6331922

## BibTeX

```bibtex
@misc{abstreet_2022,
	title = {A/{B} {Street}},
	copyright = {Creative Commons Attribution-ShareAlike 4.0 International Licence (CC-BY-SA)},
	shorttitle = {a-b-street/abstreet},
	url = {https://zenodo.org/record/6331922},
	doi = {10.5281/zenodo.6331922},
	abstract = {overhaul the rat-run mode: tighten up things counting as shortcuts, keep the same path after adding a filter change the LTN route planning tool to be map-wide, not per-neighborhood place filters at non 4-way intersections shrink some cases of overlapping roads, improving geometry when OSM data is not great a first round of simplifying LTN panels when the LTN blockfinding would've crashed previously, just fallback to using more expensive blockfinding bugfix: detect existing filters on really short roads fix initial camera placement outside of the main A/B Street app},
	urldate = {2022-03-12},
	publisher = {Zenodo},
	author = {Carlino, Dustin and Li, Yuwen and Kirk, Michael and Konieczny, Mateusz and Kott, Gedalia and Bruce and Nissar, Javed and Nederlof, Trevor and Steinberg, Vinzent and Lovelace, Robin and Dejean, Marcel and Orestis and Lauzier, Rémi and Sam and Wei, Andrew and Lewis, Brian and Schmidt, Christopher and Serdyuk, Dmitriy and Czaplicki, Filip and Fullstop000 and Raymakers, Jeff and Volker, Jeremias and Huston, Kyle and Schmid, Lorenz and Shenfield, Max and Schimek, Nick and Newsome, Tim and Tobias and Andi and moo},
	month = mar,
	year = {2022},
}
```

## Notes

{{< include _notes.qmd >}}
