---
title: "New tools of the trade? The potential and pitfalls of ’Machine Learning’ and ’DAGs’ to model origin-destination data"
description: "R. Lovelace, I. Fridman-Rojas, and R. Long (2017). New tools of the trade? The potential and pitfalls of ’Machine Learning’ and ’DAGs’ to model origin-destination data. *GeoComputation 2017*."
date: "2017-09-01"
title-block-banner: false
toc: false
citation-key: "lovelace_new_2017a"
citation-type: "paper-conference"
citation-type-label: "Conference Paper"
venue: "GeoComputation 2017"
doi: ""
publication-url: ""
authors:
  - "R. Lovelace"
  - "I. Fridman-Rojas"
  - "R. Long"
abstract: "This paper explores the potential for emerging methods Machine Learning and Directed Acyclic Graphs (DAGs) to be applied to transport modelling at the origin-destination (OD) level. OD data is inherently spatial and is complex, due to the multitude of ways of allocating geographic attributes to the OD pairs (e.g. buffers and intersections with geographic representations of OD data generated using straight desire lines, shortest path algorithms or probabilistic routing). This makes their analysis an interesting geocomputational challenge, seldom tackled by geographers. The application of Machine Learning and DAG methods, developed in other fields, to this geographical data holds great potential to improve the ability to infer causality in mode split from OD data. However, there are also pitfalls to using these methods which can be black boxes, even if the code is open source, if the analyst does not understand what they are doing with the data. Based on the work we discuss ways to ensure new methods in the field are used wisely and set-out next steps for our own research."
---

**Type:** Conference Paper
**Venue:** GeoComputation 2017
**Year:** 2017

[BibTeX](entry.bib)

## Abstract

This paper explores the potential for emerging methods Machine Learning and Directed Acyclic Graphs (DAGs) to be applied to transport modelling at the origin-destination (OD) level. OD data is inherently spatial and is complex, due to the multitude of ways of allocating geographic attributes to the OD pairs (e.g. buffers and intersections with geographic representations of OD data generated using straight desire lines, shortest path algorithms or probabilistic routing). This makes their analysis an interesting geocomputational challenge, seldom tackled by geographers. The application of Machine Learning and DAG methods, developed in other fields, to this geographical data holds great potential to improve the ability to infer causality in mode split from OD data. However, there are also pitfalls to using these methods which can be black boxes, even if the code is open source, if the analyst does not understand what they are doing with the data. Based on the work we discuss ways to ensure new methods in the field are used wisely and set-out next steps for our own research.

## Citation

R. Lovelace, I. Fridman-Rojas, and R. Long (2017). New tools of the trade? The potential and pitfalls of ’Machine Learning’ and ’DAGs’ to model origin-destination data. *GeoComputation 2017*.

## BibTeX

```bibtex
@inproceedings{lovelace_new_2017a,
  title = {New Tools of the Trade? {{The}} Potential and Pitfalls of '{{Machine Learning}}' and '{{DAGs}}' to Model Origin-Destination Data},
  shorttitle = {New Tools of the Trade?},
  booktitle = {{{GeoComputation}} 2017},
  author = {Lovelace, R. and {Fridman-Rojas}, I. and Long, R.},
  year = {2017},
  month = sep,
  urldate = {2018-03-16},
  abstract = {This paper explores the potential for emerging methods Machine Learning and Directed Acyclic Graphs (DAGs) to be applied to transport modelling at the origin-destination (OD) level. OD data is inherently spatial and is complex, due to the multitude of ways of allocating geographic attributes to the OD pairs (e.g. buffers and intersections with geographic representations of OD data generated using straight desire lines, shortest path algorithms or probabilistic routing). This makes their analysis an interesting geocomputational challenge, seldom tackled by geographers. The application of Machine Learning and DAG methods, developed in other fields, to this geographical data holds great potential to improve the ability to infer causality in mode split from OD data. However, there are also pitfalls to using these methods which can be black boxes, even if the code is open source, if the analyst does not understand what they are doing with the data. Based on the work we discuss ways to ensure new methods in the field are used wisely and set-out next steps for our own research.},
  copyright = {CC0 1.0 Universal Public Domain Dedication},
  langid = {english},
  file = {/home/robin/Zotero/storage/KXRLBEHU/Lovelace et al. - 2017 - New tools of the trade The potential and pitfalls.pdf;/home/robin/Zotero/storage/4ASZ78RW/124286.html}
}
```

## Notes

{{< include _notes.qmd >}}
